//! Persistent keyboard, mouse, and touchpad settings for a niri session.
//!
//! The service traverses niri's positional include graph and owns only one
//! final managed include. A same-directory candidate is validated by niri
//! before either live file changes; niri then applies the change through config
//! hot reload.

use kdl::{KdlDocument, KdlNode, KdlValue};
use std::collections::HashSet;
use std::fmt;
use std::io::Read as _;
#[cfg(unix)]
use std::io::{BufRead as _, Write as _};
use std::path::{Path, PathBuf};
use std::process::{Command, ExitStatus, Stdio};
use std::sync::atomic::{AtomicU64, Ordering};

static CANDIDATE_SEQUENCE: AtomicU64 = AtomicU64::new(0);
const MANAGED_CONFIG_NAME: &str = ".rmac-input.kdl";
const MANAGED_HEADER: &str = "// Managed by rmac System Settings. Do not edit this file by hand.";
const MAX_INCLUDE_DEPTH: usize = 10;
const MAX_CONFIG_FILES: usize = 64;
const MAX_CONFIG_BYTES: u64 = 2 * 1024 * 1024;
const MAX_GRAPH_BYTES: u64 = 8 * 1024 * 1024;
const MAX_COMMAND_OUTPUT_BYTES: usize = 4 * 1024 * 1024;
const COMMAND_TIMEOUT: std::time::Duration = std::time::Duration::from_secs(10);
#[cfg(unix)]
const RELOAD_TIMEOUT: std::time::Duration = std::time::Duration::from_secs(3);

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub enum AccelProfile {
    #[default]
    Adaptive,
    Flat,
}

impl AccelProfile {
    pub fn label(self) -> &'static str {
        match self {
            Self::Adaptive => "Adaptive",
            Self::Flat => "Flat",
        }
    }

    fn id(self) -> &'static str {
        match self {
            Self::Adaptive => "adaptive",
            Self::Flat => "flat",
        }
    }
}

#[derive(Clone, Debug, PartialEq)]
pub struct KeyboardSettings {
    pub repeat_delay_ms: u32,
    pub repeat_rate: u32,
    pub numlock: bool,
    pub xkb_override: Option<XkbOverride>,
}

impl Default for KeyboardSettings {
    fn default() -> Self {
        Self {
            repeat_delay_ms: 600,
            repeat_rate: 25,
            numlock: false,
            xkb_override: None,
        }
    }
}

#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct XkbOverride {
    pub rules: String,
    pub layout: String,
    pub model: String,
    pub variant: String,
    pub options: Option<String>,
    pub file: Option<String>,
}

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub enum KeyboardLayoutAuthority {
    SystemLocaled,
    NiriConfig,
    IncludedConfig,
    #[default]
    Unavailable,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub enum DeviceKind {
    Keyboard,
    Mouse,
    Touchpad,
    Trackpoint,
    Trackball,
    Tablet,
    Touchscreen,
    Other,
}

impl DeviceKind {
    pub fn label(self) -> &'static str {
        match self {
            Self::Keyboard => "Keyboard",
            Self::Mouse => "Mouse",
            Self::Touchpad => "Trackpad",
            Self::Trackpoint => "Pointing Stick",
            Self::Trackball => "Trackball",
            Self::Tablet => "Tablet",
            Self::Touchscreen => "Touchscreen",
            Self::Other => "Input Device",
        }
    }
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct InputDevice {
    /// Ephemeral kernel event identity. Never persisted as a hardware identity.
    pub id: String,
    pub name: String,
    pub kind: DeviceKind,
}

#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub enum DeviceOverrideCapability {
    #[default]
    Unsupported,
}

impl DeviceOverrideCapability {
    pub fn detail(&self) -> &'static str {
        match self {
            Self::Unsupported => {
                "This niri version applies settings by device type and does not support individual-device overrides."
            }
        }
    }
}

#[derive(Clone, Debug, PartialEq)]
pub struct PointerSettings {
    pub enabled: bool,
    pub natural_scroll: bool,
    pub accel_speed: f64,
    pub accel_profile: AccelProfile,
    pub left_handed: bool,
    pub middle_emulation: bool,
}

impl Default for PointerSettings {
    fn default() -> Self {
        Self {
            enabled: true,
            natural_scroll: false,
            accel_speed: 0.0,
            accel_profile: AccelProfile::Adaptive,
            left_handed: false,
            middle_emulation: false,
        }
    }
}

#[derive(Clone, Debug, Default, PartialEq)]
pub struct TouchpadSettings {
    pub pointer: PointerSettings,
    pub tap_to_click: bool,
    pub disable_while_typing: bool,
    pub drag_lock: bool,
}

#[derive(Clone, Debug, Default, PartialEq)]
pub struct InputSettings {
    pub keyboard: KeyboardSettings,
    pub mouse: PointerSettings,
    pub touchpad: TouchpadSettings,
}

#[derive(Clone, Debug, Default, PartialEq)]
pub struct Snapshot {
    pub available: bool,
    pub can_configure: bool,
    pub config_path: Option<PathBuf>,
    pub detail: Option<String>,
    pub keyboard_layout_authority: KeyboardLayoutAuthority,
    pub settings: InputSettings,
    pub included_files: usize,
    pub devices: Vec<InputDevice>,
    pub device_detail: Option<String>,
    pub device_overrides: DeviceOverrideCapability,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum WatchEvent {
    Changed,
    WatchError(String),
}

#[derive(Debug)]
pub struct Error {
    operation: &'static str,
    detail: String,
}

impl Error {
    fn new(operation: &'static str, detail: impl Into<String>) -> Self {
        Self {
            operation,
            detail: detail.into(),
        }
    }
}

impl fmt::Display for Error {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(formatter, "could not {}: {}", self.operation, self.detail)
    }
}

impl std::error::Error for Error {}

#[derive(Debug)]
struct ConfigLocation {
    path: PathBuf,
    writable_user_config: bool,
}

#[derive(Debug)]
struct Authority {
    main_path: PathBuf,
    main_source: String,
    managed_path: PathBuf,
    managed_source: Option<String>,
    has_managed_include: bool,
    safe_to_write: bool,
    detail: Option<String>,
    effective: EffectiveConfig,
    files: Vec<ConfigFile>,
    missing_optional_files: Vec<PathBuf>,
}

#[derive(Debug)]
struct ConfigFile {
    path: PathBuf,
    source: String,
}

#[derive(Clone, Debug, Default)]
struct EffectiveConfig {
    settings: InputSettings,
    mouse_node: Option<KdlNode>,
    touchpad_node: Option<KdlNode>,
    xkb_from_include: bool,
}

#[derive(Default)]
struct GraphState {
    effective: EffectiveConfig,
    files: Vec<ConfigFile>,
    missing_optional_files: Vec<PathBuf>,
    total_bytes: u64,
    stack: HashSet<PathBuf>,
}

/// Read effective values after recursively applying niri's positional include
/// graph and its non-merging pointing-device sections.
pub fn snapshot() -> Result<Snapshot, Error> {
    let Some(location) = config_path()? else {
        let (devices, device_detail) = system_devices();
        return Ok(Snapshot {
            detail: Some("No existing niri configuration was found.".into()),
            devices,
            device_detail,
            ..Snapshot::default()
        });
    };
    let available = niri_available();
    if available {
        validate_current_config(&location.path)?;
    }
    let authority = load_authority(&location)?;
    Ok(snapshot_from_authority(authority, available))
}

/// Validate and persist all supported input settings as one transaction.
pub fn save(settings: &InputSettings) -> Result<Snapshot, Error> {
    validate_settings(settings)?;
    let Some(location) = config_path()? else {
        return Err(Error::new(
            "save input settings",
            "no existing niri configuration was found",
        ));
    };
    let authority = load_authority(&location)?;
    let available = niri_available();
    if !available {
        return Err(Error::new(
            "save input settings",
            "input controls require the niri compositor on Linux",
        ));
    }
    if !authority.safe_to_write {
        return Err(Error::new(
            "save input settings",
            authority.detail.unwrap_or_else(|| {
                "input configuration requires a writable user niri configuration".into()
            }),
        ));
    }
    save_with_authority(authority, settings)
}

/// Watch Linux input hotplug. Niri `ConfigLoaded` remains the authoritative
/// refresh hint for changes anywhere in the configuration include graph.
pub async fn watch(sender: async_channel::Sender<WatchEvent>) -> Result<(), Error> {
    system_watch(sender).await
}

#[cfg(target_os = "linux")]
async fn system_watch(sender: async_channel::Sender<WatchEvent>) -> Result<(), Error> {
    use notify::Watcher as _;

    let callback = sender.clone();
    let mut watcher = notify::recommended_watcher(move |event: notify::Result<notify::Event>| {
        let update = match event {
            Ok(event) if matches!(event.kind, notify::EventKind::Access(_)) => return,
            Ok(_) => WatchEvent::Changed,
            Err(error) => WatchEvent::WatchError(error.to_string()),
        };
        let _ = callback.try_send(update);
    })
    .map_err(|error| Error::new("watch Linux input devices", error.to_string()))?;
    watcher
        .watch(Path::new("/dev/input"), notify::RecursiveMode::NonRecursive)
        .map_err(|error| Error::new("watch Linux input devices", error.to_string()))?;
    sender.closed().await;
    Ok(())
}

#[cfg(not(target_os = "linux"))]
async fn system_watch(_: async_channel::Sender<WatchEvent>) -> Result<(), Error> {
    Err(Error::new(
        "watch input devices",
        "live input-device watching is available only on Linux",
    ))
}

fn config_path() -> Result<Option<ConfigLocation>, Error> {
    if let Some(path) = std::env::var_os("NIRI_CONFIG")
        .filter(|value| !value.is_empty())
        .map(PathBuf::from)
    {
        if !path.is_absolute() {
            return Err(Error::new(
                "resolve the niri configuration",
                "NIRI_CONFIG must be an absolute path",
            ));
        }
        return Ok(path.is_file().then_some(ConfigLocation {
            path,
            writable_user_config: true,
        }));
    }

    let home = std::env::var_os("HOME")
        .map(PathBuf::from)
        .ok_or_else(|| Error::new("resolve the niri configuration", "HOME is not set"))?;
    let path = match std::env::var_os("XDG_CONFIG_HOME").map(PathBuf::from) {
        Some(xdg) if xdg.is_absolute() => xdg.join("niri/config.kdl"),
        _ => home.join(".config/niri/config.kdl"),
    };
    if path.is_file() {
        return Ok(Some(ConfigLocation {
            path,
            writable_user_config: true,
        }));
    }
    let system = PathBuf::from("/etc/niri/config.kdl");
    Ok(system.is_file().then_some(ConfigLocation {
        path: system,
        writable_user_config: false,
    }))
}

fn load_authority(location: &ConfigLocation) -> Result<Authority, Error> {
    let main_path = normalize_absolute(&location.path)?;
    let mut graph = GraphState::default();
    traverse_config(&main_path, 0, &mut graph)?;
    let main_source = graph
        .files
        .first()
        .map(|file| file.source.clone())
        .ok_or_else(|| Error::new("read the niri configuration", "the graph is empty"))?;
    let main = KdlDocument::parse_v1(&main_source)
        .map_err(|error| Error::new("parse the niri configuration", format!("{error}")))?;
    let managed_path = main_path.with_file_name(MANAGED_CONFIG_NAME);
    let mut managed_include_indexes = Vec::new();
    for (index, node) in main.nodes().iter().enumerate() {
        if node.name().value() == "include" && include_path(node, &main_path)?.path == managed_path
        {
            managed_include_indexes.push((index, node));
        }
    }
    let has_managed_include = managed_include_indexes.len() == 1
        && managed_include_indexes[0].0 + 1 == main.nodes().len()
        && managed_include_indexes[0].1.len() == 1
        && managed_include_indexes[0].1.children().is_none()
        && managed_include_indexes[0]
            .1
            .get(0)
            .and_then(KdlValue::as_string)
            == Some(MANAGED_CONFIG_NAME);
    let managed_graph_references = graph
        .files
        .iter()
        .filter(|file| file.path == managed_path)
        .count()
        + graph
            .missing_optional_files
            .iter()
            .filter(|path| **path == managed_path)
            .count();
    let include_is_ambiguous = managed_graph_references != usize::from(has_managed_include)
        || managed_include_indexes.len() > 1
        || managed_include_indexes
            .first()
            .is_some_and(|(index, node)| {
                *index + 1 != main.nodes().len()
                    || node.len() != 1
                    || node.children().is_some()
                    || node.get(0).and_then(KdlValue::as_string) != Some(MANAGED_CONFIG_NAME)
            });

    let managed_source = match std::fs::symlink_metadata(&managed_path) {
        Ok(metadata) if metadata.file_type().is_symlink() => None,
        Ok(_) => Some(read_bounded_config(&managed_path)?),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => None,
        Err(error) => {
            return Err(Error::new(
                "inspect the managed input configuration",
                error.to_string(),
            ));
        }
    };
    let managed_is_owned = managed_source.as_deref().is_none_or(|source| {
        source
            .strip_prefix(MANAGED_HEADER)
            .is_some_and(|body| body.is_empty() || body.starts_with('\n'))
    });
    if managed_is_owned {
        if let Some(source) = managed_source.as_deref() {
            parse_managed_document(source)?;
        }
    }

    if has_managed_include
        && managed_source.as_deref().is_some_and(|managed| {
            graph
                .files
                .iter()
                .filter(|file| file.path == managed_path)
                .any(|file| file.source != managed)
        })
    {
        return Err(Error::new(
            "read the managed input configuration",
            "the managed file changed while the include graph was being read",
        ));
    }
    let main_is_symlink = std::fs::symlink_metadata(&main_path)
        .map(|metadata| metadata.file_type().is_symlink())
        .unwrap_or(true);
    let safe_to_write = location.writable_user_config
        && !main_is_symlink
        && !include_is_ambiguous
        && managed_is_owned
        && !std::fs::symlink_metadata(&managed_path)
            .is_ok_and(|metadata| metadata.file_type().is_symlink());
    let detail = if !location.writable_user_config {
        Some("niri is using the system configuration; create a user configuration before changing input settings.".into())
    } else if main_is_symlink {
        Some(
            "The main niri configuration is a symbolic link and will not be replaced by rmac."
                .into(),
        )
    } else if include_is_ambiguous {
        Some(
            "The rmac input include must appear exactly once as the final top-level niri node."
                .into(),
        )
    } else if !managed_is_owned {
        Some(format!(
            "{} exists but is not owned by rmac.",
            managed_path.display()
        ))
    } else if !safe_to_write {
        Some(
            "The managed input configuration is a symbolic link and will not be replaced by rmac."
                .into(),
        )
    } else if !has_managed_include {
        Some("Input values are effective from the current include graph and have not yet been placed under isolated rmac ownership.".into())
    } else {
        None
    };
    Ok(Authority {
        main_path,
        main_source,
        managed_path,
        managed_source,
        has_managed_include,
        safe_to_write,
        detail,
        effective: graph.effective,
        files: graph.files,
        missing_optional_files: graph.missing_optional_files,
    })
}

fn snapshot_from_authority(authority: Authority, available: bool) -> Snapshot {
    let keyboard_layout_authority = if !available {
        KeyboardLayoutAuthority::Unavailable
    } else if authority.effective.settings.keyboard.xkb_override.is_some() {
        if authority.effective.xkb_from_include {
            KeyboardLayoutAuthority::IncludedConfig
        } else {
            KeyboardLayoutAuthority::NiriConfig
        }
    } else {
        KeyboardLayoutAuthority::SystemLocaled
    };
    let (devices, device_detail) = system_devices();
    Snapshot {
        available,
        can_configure: available && authority.safe_to_write,
        config_path: Some(authority.main_path),
        detail: if available {
            authority.detail
        } else {
            Some("Input controls require the niri compositor on Linux.".into())
        },
        keyboard_layout_authority,
        settings: authority.effective.settings,
        included_files: authority.files.len().saturating_sub(1),
        devices,
        device_detail,
        device_overrides: DeviceOverrideCapability::Unsupported,
    }
}

fn apply_input(input: &KdlDocument, effective: &mut EffectiveConfig) {
    if let Some(keyboard) = input.get("keyboard").and_then(KdlNode::children) {
        effective.settings.keyboard.repeat_delay_ms = integer(keyboard, "repeat-delay")
            .and_then(|value| u32::try_from(value).ok())
            .unwrap_or(effective.settings.keyboard.repeat_delay_ms);
        effective.settings.keyboard.repeat_rate = integer(keyboard, "repeat-rate")
            .and_then(|value| u32::try_from(value).ok())
            .unwrap_or(effective.settings.keyboard.repeat_rate);
        if let Some(value) = flag(keyboard, "numlock") {
            effective.settings.keyboard.numlock = value;
        }
        if let Some(xkb) = keyboard.get("xkb").and_then(KdlNode::children) {
            let override_ = XkbOverride {
                rules: string(xkb, "rules").unwrap_or_default().to_owned(),
                layout: string(xkb, "layout").unwrap_or_default().to_owned(),
                model: string(xkb, "model").unwrap_or_default().to_owned(),
                variant: string(xkb, "variant").unwrap_or_default().to_owned(),
                options: string(xkb, "options").map(str::to_owned),
                file: string(xkb, "file").map(str::to_owned),
            };
            effective.settings.keyboard.xkb_override =
                (override_ != XkbOverride::default()).then_some(override_);
        }
    }
    if let Some(mouse) = input.get("mouse") {
        effective.settings.mouse = PointerSettings::default();
        if let Some(children) = mouse.children() {
            read_pointer(children, &mut effective.settings.mouse);
        }
        effective.mouse_node = Some(mouse.clone());
    }
    if let Some(touchpad_node) = input.get("touchpad") {
        effective.settings.touchpad = TouchpadSettings::default();
        if let Some(touchpad) = touchpad_node.children() {
            read_pointer(touchpad, &mut effective.settings.touchpad.pointer);
            effective.settings.touchpad.tap_to_click = flag(touchpad, "tap").unwrap_or(false);
            effective.settings.touchpad.disable_while_typing =
                flag(touchpad, "dwt").unwrap_or(false);
            effective.settings.touchpad.drag_lock = flag(touchpad, "drag-lock").unwrap_or(false);
        }
        effective.touchpad_node = Some(touchpad_node.clone());
    }
}

fn traverse_config(path: &Path, depth: usize, state: &mut GraphState) -> Result<(), Error> {
    if depth >= MAX_INCLUDE_DEPTH {
        return Err(Error::new(
            "traverse the niri include graph",
            "the include graph exceeds niri's ten-level recursion limit",
        ));
    }
    let path = normalize_absolute(path)?;
    if !state.stack.insert(path.clone()) {
        return Err(Error::new(
            "traverse the niri include graph",
            format!("recursive include detected at {}", path.display()),
        ));
    }
    if state.files.len() >= MAX_CONFIG_FILES {
        return Err(Error::new(
            "traverse the niri include graph",
            "the include graph exceeds the 64-file safety limit",
        ));
    }
    let source = read_bounded_config(&path)?;
    state.total_bytes = state
        .total_bytes
        .checked_add(source.len() as u64)
        .ok_or_else(|| Error::new("traverse the niri include graph", "size overflow"))?;
    if state.total_bytes > MAX_GRAPH_BYTES {
        return Err(Error::new(
            "traverse the niri include graph",
            "the include graph exceeds the 8 MiB safety limit",
        ));
    }
    state.files.push(ConfigFile {
        path: path.clone(),
        source: source.clone(),
    });
    let document = KdlDocument::parse_v1(&source).map_err(|error| {
        Error::new(
            "parse the niri include graph",
            format!("{}: {error}", path.display()),
        )
    })?;
    let mut saw_input = false;
    for node in document.nodes() {
        match node.name().value() {
            "include" => {
                let include = include_path(node, &path)?;
                match std::fs::metadata(&include.path) {
                    Ok(_) => traverse_config(&include.path, depth + 1, state)?,
                    Err(error)
                        if include.optional && error.kind() == std::io::ErrorKind::NotFound =>
                    {
                        state.missing_optional_files.push(include.path);
                    }
                    Err(error) => {
                        return Err(Error::new(
                            "read the niri include graph",
                            format!("{}: {error}", include.path.display()),
                        ));
                    }
                }
            }
            "input" => {
                if saw_input {
                    return Err(Error::new(
                        "parse the niri include graph",
                        format!(
                            "{} contains more than one top-level input block",
                            path.display()
                        ),
                    ));
                }
                saw_input = true;
                if let Some(input) = node.children() {
                    let sets_xkb = input
                        .get("keyboard")
                        .and_then(KdlNode::children)
                        .is_some_and(|keyboard| keyboard.get("xkb").is_some());
                    apply_input(input, &mut state.effective);
                    if sets_xkb {
                        state.effective.xkb_from_include =
                            depth > 0 && state.effective.settings.keyboard.xkb_override.is_some();
                    }
                }
            }
            _ => {}
        }
    }
    state.stack.remove(&path);
    Ok(())
}

struct IncludePath {
    path: PathBuf,
    optional: bool,
}

fn include_path(node: &KdlNode, source_path: &Path) -> Result<IncludePath, Error> {
    let raw = node.get(0).and_then(KdlValue::as_string).ok_or_else(|| {
        Error::new(
            "parse the niri include graph",
            format!(
                "{} has an include without a string path",
                source_path.display()
            ),
        )
    })?;
    if node.children().is_some() || node.len() != usize::from(node.get("optional").is_some()) + 1 {
        return Err(Error::new(
            "parse the niri include graph",
            format!(
                "{} has an include with unsupported arguments",
                source_path.display()
            ),
        ));
    }
    let optional = match node.get("optional") {
        Some(value) => value.as_bool().ok_or_else(|| {
            Error::new(
                "parse the niri include graph",
                format!(
                    "{} has a non-boolean optional include",
                    source_path.display()
                ),
            )
        })?,
        None => false,
    };
    let raw_path = PathBuf::from(raw);
    let expanded = if let Ok(rest) = raw_path.strip_prefix("~") {
        let home = std::env::var_os("HOME")
            .map(PathBuf::from)
            .ok_or_else(|| Error::new("expand a niri include", "HOME is not set"))?;
        home.join(rest)
    } else if raw_path.is_absolute() {
        raw_path
    } else {
        source_path
            .parent()
            .unwrap_or_else(|| Path::new("/"))
            .join(raw_path)
    };
    Ok(IncludePath {
        path: normalize_absolute(&expanded)?,
        optional,
    })
}

fn normalize_absolute(path: &Path) -> Result<PathBuf, Error> {
    use std::path::Component;

    if !path.is_absolute() {
        return Err(Error::new(
            "normalize the niri configuration path",
            format!("{} is not absolute", path.display()),
        ));
    }
    let mut normalized = PathBuf::new();
    for component in path.components() {
        match component {
            Component::RootDir | Component::Prefix(_) => normalized.push(component.as_os_str()),
            Component::CurDir => {}
            Component::ParentDir => {
                if !normalized.pop() {
                    return Err(Error::new(
                        "normalize the niri configuration path",
                        "the path escapes the filesystem root",
                    ));
                }
            }
            Component::Normal(component) => normalized.push(component),
        }
    }
    Ok(normalized)
}

fn read_bounded_config(path: &Path) -> Result<String, Error> {
    let file = std::fs::File::open(path).map_err(|error| {
        Error::new(
            "read the niri input configuration",
            format!("{}: {error}", path.display()),
        )
    })?;
    if file
        .metadata()
        .map_err(|error| Error::new("inspect the niri input configuration", error.to_string()))?
        .len()
        > MAX_CONFIG_BYTES
    {
        return Err(Error::new(
            "read the niri input configuration",
            format!("{} exceeds the 2 MiB safety limit", path.display()),
        ));
    }
    let mut bytes = Vec::new();
    file.take(MAX_CONFIG_BYTES + 1)
        .read_to_end(&mut bytes)
        .map_err(|error| Error::new("read the niri input configuration", error.to_string()))?;
    if bytes.len() as u64 > MAX_CONFIG_BYTES {
        return Err(Error::new(
            "read the niri input configuration",
            format!("{} exceeds the 2 MiB safety limit", path.display()),
        ));
    }
    String::from_utf8(bytes).map_err(|_| {
        Error::new(
            "read the niri input configuration",
            format!("{} is not valid UTF-8", path.display()),
        )
    })
}

#[cfg(target_os = "linux")]
fn system_devices() -> (Vec<InputDevice>, Option<String>) {
    const MAX_DEVICES: usize = 128;
    let directory = Path::new("/sys/class/input");
    let entries = match std::fs::read_dir(directory) {
        Ok(entries) => entries,
        Err(error) => {
            return (
                Vec::new(),
                Some(format!("Kernel input devices could not be read: {error}")),
            );
        }
    };
    let mut devices = Vec::new();
    let mut truncated = false;
    for entry in entries.flatten() {
        let id = entry.file_name().to_string_lossy().into_owned();
        if !id.strip_prefix("event").is_some_and(|suffix| {
            !suffix.is_empty() && suffix.chars().all(|ch| ch.is_ascii_digit())
        }) {
            continue;
        }
        if devices.len() == MAX_DEVICES {
            truncated = true;
            break;
        }
        let device = entry.path().join("device");
        let name = read_small_text(&device.join("name"), 4096)
            .map(|name| name.trim().to_owned())
            .filter(|name| !name.is_empty())
            .unwrap_or_else(|| "Unnamed input device".into());
        let properties = read_small_text(&entry.path().join("dev"), 64)
            .and_then(|dev| {
                let udev = Path::new("/run/udev/data").join(format!("c{}", dev.trim()));
                read_small_text(&udev, 64 * 1024)
            })
            .unwrap_or_default();
        let kind = classify_device(&name, &properties);
        devices.push(InputDevice { id, name, kind });
    }
    devices.sort_by(|left, right| {
        left.kind
            .cmp(&right.kind)
            .then_with(|| left.name.cmp(&right.name))
            .then_with(|| left.id.cmp(&right.id))
    });
    let detail = truncated.then(|| "Only the first 128 kernel input devices are shown.".into());
    (devices, detail)
}

#[cfg(not(target_os = "linux"))]
fn system_devices() -> (Vec<InputDevice>, Option<String>) {
    (
        Vec::new(),
        Some("Live input-device inventory is available only on Linux.".into()),
    )
}

#[cfg(target_os = "linux")]
fn read_small_text(path: &Path, limit: u64) -> Option<String> {
    let mut bytes = Vec::new();
    std::fs::File::open(path)
        .ok()?
        .take(limit + 1)
        .read_to_end(&mut bytes)
        .ok()?;
    if bytes.len() as u64 > limit {
        return None;
    }
    String::from_utf8(bytes).ok()
}

#[cfg(any(target_os = "linux", test))]
fn classify_device(name: &str, properties: &str) -> DeviceKind {
    let property = |key: &str| {
        let expected = format!("E:{key}=1");
        properties.lines().any(|line| line == expected)
    };
    if property("ID_INPUT_TOUCHPAD") {
        DeviceKind::Touchpad
    } else if property("ID_INPUT_TOUCHSCREEN") {
        DeviceKind::Touchscreen
    } else if property("ID_INPUT_TABLET") {
        DeviceKind::Tablet
    } else if property("ID_INPUT_POINTINGSTICK") {
        DeviceKind::Trackpoint
    } else if property("ID_INPUT_TRACKBALL") {
        DeviceKind::Trackball
    } else if property("ID_INPUT_MOUSE") {
        DeviceKind::Mouse
    } else if property("ID_INPUT_KEYBOARD") {
        DeviceKind::Keyboard
    } else {
        let name = name.to_ascii_lowercase();
        if name.contains("touchpad") {
            DeviceKind::Touchpad
        } else if name.contains("touchscreen") {
            DeviceKind::Touchscreen
        } else if name.contains("trackpoint") || name.contains("pointing stick") {
            DeviceKind::Trackpoint
        } else if name.contains("trackball") {
            DeviceKind::Trackball
        } else if name.contains("mouse") {
            DeviceKind::Mouse
        } else if name.contains("keyboard") || name.contains("kbd") {
            DeviceKind::Keyboard
        } else {
            DeviceKind::Other
        }
    }
}

fn read_pointer(document: &KdlDocument, pointer: &mut PointerSettings) {
    pointer.enabled = !flag(document, "off").unwrap_or(false);
    pointer.natural_scroll = flag(document, "natural-scroll").unwrap_or(false);
    pointer.left_handed = flag(document, "left-handed").unwrap_or(false);
    pointer.middle_emulation = flag(document, "middle-emulation").unwrap_or(false);
    pointer.accel_speed = number(document, "accel-speed").unwrap_or(pointer.accel_speed);
    pointer.accel_profile = match string(document, "accel-profile") {
        Some("flat") => AccelProfile::Flat,
        _ => AccelProfile::Adaptive,
    };
}

fn flag(document: &KdlDocument, name: &str) -> Option<bool> {
    document
        .nodes()
        .iter()
        .rev()
        .find(|node| node.name().value() == name)
        .map(|node| node.get(0).and_then(KdlValue::as_bool).unwrap_or(true))
}

fn integer(document: &KdlDocument, name: &str) -> Option<i128> {
    document.get_arg(name).and_then(KdlValue::as_integer)
}

fn number(document: &KdlDocument, name: &str) -> Option<f64> {
    document.get_arg(name).and_then(|value| {
        value
            .as_float()
            .or_else(|| value.as_integer().map(|n| n as f64))
    })
}

fn string<'a>(document: &'a KdlDocument, name: &str) -> Option<&'a str> {
    document.get_arg(name).and_then(KdlValue::as_string)
}

fn validate_settings(settings: &InputSettings) -> Result<(), Error> {
    if !(100..=2_000).contains(&settings.keyboard.repeat_delay_ms) {
        return Err(Error::new(
            "validate keyboard settings",
            "repeat delay must be between 100 and 2000 ms",
        ));
    }
    if !(1..=100).contains(&settings.keyboard.repeat_rate) {
        return Err(Error::new(
            "validate keyboard settings",
            "repeat rate must be between 1 and 100 characters per second",
        ));
    }
    for (device, pointer) in [
        ("mouse", &settings.mouse),
        ("touchpad", &settings.touchpad.pointer),
    ] {
        if !pointer.accel_speed.is_finite() || !(-1.0..=1.0).contains(&pointer.accel_speed) {
            return Err(Error::new(
                "validate pointer settings",
                format!("{device} tracking speed must be between -1 and 1"),
            ));
        }
    }
    Ok(())
}

fn save_with_authority(authority: Authority, settings: &InputSettings) -> Result<Snapshot, Error> {
    if authority.effective.settings == *settings {
        return Ok(snapshot_from_authority(authority, true));
    }
    let managed = update_managed_source(&authority, settings)?;
    ensure_authority_unchanged(&authority)?;
    validate_candidate(&authority, &managed)?;
    ensure_authority_unchanged(&authority)?;
    let mut reload_witness = ReloadWitness::open()?;
    ensure_authority_unchanged(&authority)?;

    let previous_managed = authority.managed_source.as_deref().map(str::as_bytes);
    if let Some(previous) = previous_managed {
        let backup = authority
            .managed_path
            .with_file_name(format!("{MANAGED_CONFIG_NAME}.last-good"));
        rmac_storage::atomic_write(&backup, previous).map_err(|error| {
            Error::new(
                "save the last-known-good input configuration",
                error.to_string(),
            )
        })?;
    }
    rmac_storage::atomic_write(&authority.managed_path, managed.as_bytes())
        .map_err(|error| Error::new("save the managed input configuration", error.to_string()))?;
    if !authority.has_managed_include {
        let main = main_with_managed_include(&authority.main_source, MANAGED_CONFIG_NAME);
        if let Err(error) = rmac_storage::atomic_write(&authority.main_path, main.as_bytes()) {
            let rollback = restore_managed(&authority.managed_path, previous_managed);
            return Err(Error::new(
                "enable the managed input configuration",
                match rollback {
                    Ok(()) => error.to_string(),
                    Err(rollback) => format!(
                        "{error}; restoring the previous managed file also failed: {rollback}"
                    ),
                },
            ));
        }
    }

    if let Err(error) = reload_witness.wait_for_reload() {
        let rollback = rollback_input_transaction(
            &authority,
            !authority.has_managed_include,
            previous_managed,
        );
        return Err(Error::new(
            "verify niri adopted the input configuration",
            match rollback {
                Ok(()) => format!("{error}; the previous configuration was restored"),
                Err(rollback) => format!("{error}; automatic rollback failed: {rollback}"),
            },
        ));
    }

    let snapshot = match snapshot() {
        Ok(snapshot) => snapshot,
        Err(error) => {
            let rollback = rollback_input_transaction(
                &authority,
                !authority.has_managed_include,
                previous_managed,
            );
            return Err(Error::new(
                "verify the saved input configuration",
                match rollback {
                    Ok(()) => format!("{error}; the previous configuration was restored"),
                    Err(rollback) => format!("{error}; automatic rollback failed: {rollback}"),
                },
            ));
        }
    };
    if snapshot.settings != *settings {
        let rollback = rollback_input_transaction(
            &authority,
            !authority.has_managed_include,
            previous_managed,
        );
        return Err(Error::new(
            "verify the saved input configuration",
            match rollback {
                Ok(()) => "the complete saved values did not match; the previous configuration was restored".into(),
                Err(rollback) => format!(
                    "the complete saved values did not match, and automatic rollback failed: {rollback}"
                ),
            },
        ));
    }
    Ok(snapshot)
}

fn update_managed_source(authority: &Authority, settings: &InputSettings) -> Result<String, Error> {
    let mut document = match authority.managed_source.as_deref() {
        Some(source) => parse_managed_document(source)?,
        None => KdlDocument::new(),
    };
    let input = ensure_children(&mut document, "input");
    if settings.keyboard != authority.effective.settings.keyboard || input.get("keyboard").is_some()
    {
        let keyboard = ensure_children(input, "keyboard");
        replace_value(
            keyboard,
            "repeat-delay",
            i128::from(settings.keyboard.repeat_delay_ms),
        );
        replace_value(
            keyboard,
            "repeat-rate",
            i128::from(settings.keyboard.repeat_rate),
        );
        replace_explicit_flag(keyboard, "numlock", settings.keyboard.numlock)?;
    }

    if settings.mouse != authority.effective.settings.mouse || input.get("mouse").is_some() {
        if input.get("mouse").is_none() {
            input.nodes_mut().push(
                authority
                    .effective
                    .mouse_node
                    .clone()
                    .unwrap_or_else(|| input_node("mouse")),
            );
        }
        let mouse = input
            .get_mut("mouse")
            .expect("mouse node exists")
            .ensure_children();
        write_pointer(mouse, &settings.mouse);
    }

    if settings.touchpad != authority.effective.settings.touchpad || input.get("touchpad").is_some()
    {
        if input.get("touchpad").is_none() {
            input.nodes_mut().push(
                authority
                    .effective
                    .touchpad_node
                    .clone()
                    .unwrap_or_else(|| input_node("touchpad")),
            );
        }
        let touchpad = input
            .get_mut("touchpad")
            .expect("touchpad node exists")
            .ensure_children();
        write_pointer(touchpad, &settings.touchpad.pointer);
        replace_flag(touchpad, "tap", settings.touchpad.tap_to_click);
        replace_flag(touchpad, "dwt", settings.touchpad.disable_while_typing);
        replace_flag(touchpad, "drag-lock", settings.touchpad.drag_lock);
    }
    document.ensure_v1();
    Ok(format!("{MANAGED_HEADER}\n{document}"))
}

fn input_node(name: &str) -> KdlNode {
    let mut node = KdlNode::new(name);
    node.set_children(KdlDocument::new());
    node
}

fn parse_managed_document(source: &str) -> Result<KdlDocument, Error> {
    let body = if source == MANAGED_HEADER {
        ""
    } else {
        source
            .strip_prefix(MANAGED_HEADER)
            .and_then(|body| body.strip_prefix('\n'))
            .ok_or_else(|| {
                Error::new(
                    "parse the managed input configuration",
                    "the exact rmac ownership header is missing",
                )
            })?
    };
    let document = KdlDocument::parse_v1(body)
        .map_err(|error| Error::new("parse the managed input configuration", format!("{error}")))?;
    if document.nodes().len() > 1
        || document
            .nodes()
            .iter()
            .any(|node| node.name().value() != "input" || !node.is_empty())
    {
        return Err(Error::new(
            "parse the managed input configuration",
            "the managed file may contain only one argument-free input block",
        ));
    }
    if let Some(input) = document.get("input").and_then(KdlNode::children) {
        let mut sections = HashSet::new();
        for node in input.nodes() {
            let name = node.name().value();
            if !matches!(name, "keyboard" | "mouse" | "touchpad")
                || !node.is_empty()
                || !sections.insert(name)
            {
                return Err(Error::new(
                    "parse the managed input configuration",
                    "the managed input block contains an unsupported or duplicate device section",
                ));
            }
            if name == "keyboard" {
                validate_managed_keyboard(node)?;
            }
        }
    }
    Ok(document)
}

fn validate_managed_keyboard(node: &KdlNode) -> Result<(), Error> {
    let Some(keyboard) = node.children() else {
        return Ok(());
    };
    let mut settings = HashSet::new();
    for setting in keyboard.nodes() {
        let name = setting.name().value();
        let valid_value = match name {
            "repeat-delay" | "repeat-rate" => {
                setting.len() == 1
                    && setting.get(0).and_then(KdlValue::as_integer).is_some()
                    && setting.children().is_none()
            }
            "numlock" => {
                (setting.is_empty()
                    || (setting.len() == 1 && setting.get(0).and_then(KdlValue::as_bool).is_some()))
                    && setting.children().is_none()
            }
            _ => false,
        };
        if !valid_value || !settings.insert(name) {
            return Err(Error::new(
                "parse the managed input configuration",
                "the managed keyboard section contains unsupported, duplicate, or malformed settings",
            ));
        }
    }
    Ok(())
}

fn ensure_children<'a>(document: &'a mut KdlDocument, name: &str) -> &'a mut KdlDocument {
    if document.get(name).is_none() {
        let mut node = KdlNode::new(name);
        node.set_children(KdlDocument::new());
        document.nodes_mut().push(node);
    }
    let node = document.get_mut(name).expect("node was just created");
    node.ensure_children()
}

fn write_pointer(document: &mut KdlDocument, pointer: &PointerSettings) {
    replace_flag(document, "off", !pointer.enabled);
    replace_flag(document, "natural-scroll", pointer.natural_scroll);
    replace_value(document, "accel-speed", pointer.accel_speed);
    replace_string_value(document, "accel-profile", pointer.accel_profile.id());
    replace_flag(document, "left-handed", pointer.left_handed);
    replace_flag(document, "middle-emulation", pointer.middle_emulation);
}

fn remove_named(document: &mut KdlDocument, name: &str) {
    document
        .nodes_mut()
        .retain(|node| node.name().value() != name);
}

fn replace_flag(document: &mut KdlDocument, name: &str, enabled: bool) {
    remove_named(document, name);
    if enabled {
        document.nodes_mut().push(KdlNode::new(name));
    }
}

fn replace_explicit_flag(
    document: &mut KdlDocument,
    name: &str,
    enabled: bool,
) -> Result<(), Error> {
    remove_named(document, name);
    if enabled {
        document.nodes_mut().push(KdlNode::new(name));
    } else {
        let parsed = KdlDocument::parse_v1(&format!("{name} false\n"))
            .map_err(|error| Error::new("write an explicit niri input flag", format!("{error}")))?;
        document.nodes_mut().extend(parsed.nodes().iter().cloned());
    }
    Ok(())
}

fn replace_value(document: &mut KdlDocument, name: &str, value: impl Into<kdl::KdlEntry>) {
    remove_named(document, name);
    let mut node = KdlNode::new(name);
    node.push(value);
    document.nodes_mut().push(node);
}

fn replace_string_value(document: &mut KdlDocument, name: &str, value: &str) {
    remove_named(document, name);
    let parsed = KdlDocument::parse_v1(&format!("{name} \"{value}\"\n"))
        .expect("controlled niri string settings are valid KDL v1");
    document.nodes_mut().extend(parsed.nodes().iter().cloned());
}

fn validate_candidate(authority: &Authority, managed_source: &str) -> Result<(), Error> {
    let sequence = CANDIDATE_SEQUENCE.fetch_add(1, Ordering::Relaxed);
    let managed_name = format!(
        ".rmac-input-{}-{sequence}.candidate.kdl",
        std::process::id()
    );
    let managed_candidate = authority.managed_path.with_file_name(&managed_name);
    let main_name = format!(
        ".rmac-config-{}-{sequence}.candidate.kdl",
        std::process::id()
    );
    let main_candidate = authority.main_path.with_file_name(main_name);
    let result = (|| {
        rmac_storage::atomic_write(&managed_candidate, managed_source.as_bytes())
            .map_err(|error| Error::new("write the validation candidate", error.to_string()))?;
        let main_source = if authority.has_managed_include {
            let mut document = KdlDocument::parse_v1(&authority.main_source).map_err(|error| {
                Error::new("parse the validation candidate", format!("{error}"))
            })?;
            let include = document.nodes_mut().last_mut().ok_or_else(|| {
                Error::new(
                    "prepare the validation candidate",
                    "managed include is missing",
                )
            })?;
            let value = include.get_mut(0).ok_or_else(|| {
                Error::new(
                    "prepare the validation candidate",
                    "managed include path is missing",
                )
            })?;
            *value = KdlValue::String(managed_name);
            document.ensure_v1();
            document.to_string()
        } else {
            main_with_managed_include(&authority.main_source, &managed_name)
        };
        rmac_storage::atomic_write(&main_candidate, main_source.as_bytes()).map_err(|error| {
            Error::new("write the main validation candidate", error.to_string())
        })?;
        let mut command = Command::new("niri");
        command.arg("--config").arg(&main_candidate).arg("validate");
        bounded_command_output(&mut command, "run niri validation")
    })();
    let cleanup = [&main_candidate, &managed_candidate]
        .into_iter()
        .filter_map(|path| match std::fs::remove_file(path) {
            Ok(()) => None,
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => None,
            Err(error) => Some(format!("{}: {error}", path.display())),
        })
        .collect::<Vec<_>>();
    if !cleanup.is_empty() {
        return Err(Error::new(
            "remove the input validation candidates",
            match result {
                Ok(_) => cleanup.join("; "),
                Err(error) => format!("{error}; cleanup also failed: {}", cleanup.join("; ")),
            },
        ));
    }
    let output = result?;
    if !output.status.success() {
        let detail = String::from_utf8_lossy(&output.stderr).trim().to_string();
        return Err(Error::new(
            "validate the niri configuration",
            if detail.is_empty() {
                format!("niri exited with {}", output.status)
            } else {
                detail
            },
        ));
    }
    Ok(())
}

fn main_with_managed_include(source: &str, managed_name: &str) -> String {
    let mut main = source.to_owned();
    if !main.ends_with('\n') {
        main.push('\n');
    }
    main.push_str(&format!("include \"{managed_name}\"\n"));
    main
}

fn ensure_authority_unchanged(authority: &Authority) -> Result<(), Error> {
    for file in &authority.files {
        if read_bounded_config(&file.path)? != file.source {
            return Err(Error::new(
                "save input settings",
                format!(
                    "{} changed in the niri include graph; refresh before trying again",
                    file.path.display()
                ),
            ));
        }
    }
    for path in &authority.missing_optional_files {
        match std::fs::symlink_metadata(path) {
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => {}
            Ok(_) => {
                return Err(Error::new(
                    "save input settings",
                    format!(
                        "the optional include {} appeared; refresh before trying again",
                        path.display()
                    ),
                ));
            }
            Err(error) => return Err(Error::new("save input settings", error.to_string())),
        }
    }
    match authority.managed_source.as_deref() {
        Some(expected) if read_bounded_config(&authority.managed_path)? != expected => {
            Err(Error::new(
                "save input settings",
                "the managed input configuration changed; refresh before trying again",
            ))
        }
        Some(_) => Ok(()),
        None => match std::fs::symlink_metadata(&authority.managed_path) {
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(()),
            Ok(_) => Err(Error::new(
                "save input settings",
                "the managed input path was created concurrently; refresh before trying again",
            )),
            Err(error) => Err(Error::new("save input settings", error.to_string())),
        },
    }
}

fn restore_managed(path: &Path, previous: Option<&[u8]>) -> Result<(), String> {
    match previous {
        Some(previous) => {
            rmac_storage::atomic_write(path, previous).map_err(|error| error.to_string())
        }
        None => match std::fs::remove_file(path) {
            Ok(()) => Ok(()),
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(()),
            Err(error) => Err(error.to_string()),
        },
    }
}

fn rollback_input_transaction(
    authority: &Authority,
    restore_main: bool,
    previous_managed: Option<&[u8]>,
) -> Result<(), String> {
    let main_error = restore_main
        .then(|| {
            rmac_storage::atomic_write(&authority.main_path, authority.main_source.as_bytes())
                .map_err(|error| format!("main configuration: {error}"))
        })
        .transpose()
        .err();
    let managed_error = restore_managed(&authority.managed_path, previous_managed)
        .map_err(|error| format!("managed input configuration: {error}"))
        .err();
    match (main_error, managed_error) {
        (None, None) => Ok(()),
        (Some(error), None) | (None, Some(error)) => Err(error),
        (Some(main), Some(managed)) => Err(format!("{main}; {managed}")),
    }
}

#[cfg(unix)]
struct ReloadWitness {
    reader: std::io::BufReader<std::os::unix::net::UnixStream>,
}

#[cfg(unix)]
impl ReloadWitness {
    fn open() -> Result<Self, Error> {
        let socket = std::env::var_os("NIRI_SOCKET")
            .filter(|socket| !socket.is_empty())
            .ok_or_else(|| Error::new("watch niri config adoption", "NIRI_SOCKET is not set"))?;
        let mut stream = std::os::unix::net::UnixStream::connect(PathBuf::from(socket))
            .map_err(|error| Error::new("watch niri config adoption", error.to_string()))?;
        stream
            .set_write_timeout(Some(std::time::Duration::from_millis(500)))
            .map_err(|error| Error::new("watch niri config adoption", error.to_string()))?;
        stream
            .write_all(b"\"EventStream\"\n")
            .and_then(|()| stream.flush())
            .map_err(|error| Error::new("start the niri event stream", error.to_string()))?;
        let mut reader = std::io::BufReader::new(stream);
        let deadline = std::time::Instant::now() + RELOAD_TIMEOUT;
        let reply = read_reload_json_line(&mut reader, deadline)?;
        if reply.get("Ok").is_none() {
            return Err(Error::new(
                "start the niri event stream",
                "niri rejected the event-stream request",
            ));
        }
        if next_config_load(&mut reader, deadline)? {
            return Err(Error::new(
                "watch niri config adoption",
                "niri reports that its current configuration failed to load",
            ));
        }
        Ok(Self { reader })
    }

    fn wait_for_reload(&mut self) -> Result<(), Error> {
        let failed =
            next_config_load(&mut self.reader, std::time::Instant::now() + RELOAD_TIMEOUT)?;
        if failed {
            Err(Error::new(
                "watch niri config adoption",
                "niri rejected the updated configuration",
            ))
        } else {
            Ok(())
        }
    }
}

#[cfg(not(unix))]
struct ReloadWitness;

#[cfg(not(unix))]
impl ReloadWitness {
    fn open() -> Result<Self, Error> {
        Err(Error::new(
            "watch niri config adoption",
            "niri config adoption is available only on Linux",
        ))
    }

    fn wait_for_reload(&mut self) -> Result<(), Error> {
        Err(Error::new(
            "watch niri config adoption",
            "niri config adoption is available only on Linux",
        ))
    }
}

#[cfg(unix)]
fn read_reload_json_line(
    reader: &mut std::io::BufReader<std::os::unix::net::UnixStream>,
    deadline: std::time::Instant,
) -> Result<serde_json::Value, Error> {
    loop {
        let now = std::time::Instant::now();
        if now >= deadline {
            return Err(Error::new(
                "read the niri event stream",
                "niri did not report config state within three seconds",
            ));
        }
        reader
            .get_mut()
            .set_read_timeout(Some(
                deadline
                    .saturating_duration_since(now)
                    .min(std::time::Duration::from_millis(250)),
            ))
            .map_err(|error| Error::new("read the niri event stream", error.to_string()))?;
        let mut bytes = Vec::new();
        let mut limited = reader.take(MAX_COMMAND_OUTPUT_BYTES as u64 + 1);
        match limited.read_until(b'\n', &mut bytes) {
            Ok(0) => {
                return Err(Error::new(
                    "read the niri event stream",
                    "the niri IPC socket closed",
                ));
            }
            Ok(_) if bytes.len() > MAX_COMMAND_OUTPUT_BYTES => {
                return Err(Error::new(
                    "read the niri event stream",
                    "a niri event exceeded the 4 MiB safety limit",
                ));
            }
            Ok(_) => {
                while matches!(bytes.last(), Some(b'\n' | b'\r')) {
                    bytes.pop();
                }
                return serde_json::from_slice(&bytes).map_err(|error| {
                    Error::new("decode the niri event stream", error.to_string())
                });
            }
            Err(error)
                if bytes.is_empty()
                    && matches!(
                        error.kind(),
                        std::io::ErrorKind::WouldBlock | std::io::ErrorKind::TimedOut
                    ) => {}
            Err(error) => {
                return Err(Error::new("read the niri event stream", error.to_string()));
            }
        }
    }
}

#[cfg(unix)]
fn next_config_load(
    reader: &mut std::io::BufReader<std::os::unix::net::UnixStream>,
    deadline: std::time::Instant,
) -> Result<bool, Error> {
    loop {
        let event = read_reload_json_line(reader, deadline)?;
        if let Some(failed) = config_load_failed(&event) {
            return Ok(failed);
        }
    }
}

#[cfg(any(unix, test))]
fn config_load_failed(event: &serde_json::Value) -> Option<bool> {
    event.get("ConfigLoaded")?.get("failed")?.as_bool()
}

fn niri_available() -> bool {
    if !cfg!(target_os = "linux")
        || std::env::var_os("NIRI_SOCKET").is_none_or(|socket| socket.is_empty())
    {
        return false;
    }
    let mut command = Command::new("niri");
    command.args(["msg", "--json", "version"]);
    bounded_command_output(&mut command, "contact the niri compositor")
        .is_ok_and(|output| output.status.success())
}

fn validate_current_config(path: &Path) -> Result<(), Error> {
    let mut command = Command::new("niri");
    command.arg("--config").arg(path).arg("validate");
    let output = bounded_command_output(&mut command, "validate the current niri configuration")?;
    if output.status.success() {
        return Ok(());
    }
    let detail = String::from_utf8_lossy(&output.stderr).trim().to_string();
    Err(Error::new(
        "validate the current niri configuration",
        if detail.is_empty() {
            format!("niri exited with {}", output.status)
        } else {
            detail
        },
    ))
}

struct CommandOutput {
    status: ExitStatus,
    _stdout: Vec<u8>,
    stderr: Vec<u8>,
}

fn bounded_command_output(
    command: &mut Command,
    operation: &'static str,
) -> Result<CommandOutput, Error> {
    command
        .stdin(Stdio::null())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped());
    let mut child = command
        .spawn()
        .map_err(|error| Error::new(operation, error.to_string()))?;
    let stdout = child
        .stdout
        .take()
        .ok_or_else(|| Error::new(operation, "stdout was not captured"))?;
    let stderr = child
        .stderr
        .take()
        .ok_or_else(|| Error::new(operation, "stderr was not captured"))?;
    let stdout_reader = std::thread::spawn(move || drain_bounded(stdout, MAX_COMMAND_OUTPUT_BYTES));
    let stderr_reader = std::thread::spawn(move || drain_bounded(stderr, MAX_COMMAND_OUTPUT_BYTES));
    let deadline = std::time::Instant::now() + COMMAND_TIMEOUT;
    let status = loop {
        match child.try_wait() {
            Ok(Some(status)) => break Ok(status),
            Ok(None) if std::time::Instant::now() < deadline => {
                std::thread::sleep(std::time::Duration::from_millis(25));
            }
            Ok(None) => {
                let _ = child.kill();
                let _ = child.wait();
                break Err(Error::new(
                    operation,
                    "the command did not finish within ten seconds",
                ));
            }
            Err(error) => {
                let _ = child.kill();
                let _ = child.wait();
                break Err(Error::new(operation, error.to_string()));
            }
        }
    };
    let (stdout, stdout_truncated) = stdout_reader
        .join()
        .map_err(|_| Error::new(operation, "the stdout reader stopped unexpectedly"))?
        .map_err(|error| Error::new(operation, error.to_string()))?;
    let (stderr, stderr_truncated) = stderr_reader
        .join()
        .map_err(|_| Error::new(operation, "the stderr reader stopped unexpectedly"))?
        .map_err(|error| Error::new(operation, error.to_string()))?;
    let status = status?;
    if stdout_truncated || stderr_truncated {
        return Err(Error::new(
            operation,
            "the command output exceeded the 4 MiB safety limit",
        ));
    }
    Ok(CommandOutput {
        status,
        _stdout: stdout,
        stderr,
    })
}

fn drain_bounded(mut reader: impl std::io::Read, limit: usize) -> std::io::Result<(Vec<u8>, bool)> {
    let mut captured = Vec::with_capacity(limit.min(8192));
    let mut buffer = [0_u8; 8192];
    let mut truncated = false;
    loop {
        let read = reader.read(&mut buffer)?;
        if read == 0 {
            break;
        }
        let remaining = limit.saturating_sub(captured.len());
        captured.extend_from_slice(&buffer[..read.min(remaining)]);
        truncated |= read > remaining;
    }
    Ok((captured, truncated))
}

#[cfg(test)]
mod tests {
    use super::*;

    const CONFIG: &str = r#"
input {
    keyboard {
        repeat-delay 450
        repeat-rate 32
        numlock false
        track-layout "global"
    }
    mouse {
        natural-scroll
        accel-speed -0.25
        accel-profile "flat"
        scroll-method "on-button-down"
        middle-emulation
    }
    touchpad {
        tap
        dwt false
        accel-speed 0.2
        middle-emulation
    }
    warp-mouse-to-focus
}
"#;

    fn effective(source: &str) -> EffectiveConfig {
        let document = KdlDocument::parse_v1(source).unwrap();
        let mut effective = EffectiveConfig::default();
        for node in document.nodes() {
            if node.name().value() == "input" {
                apply_input(node.children().unwrap(), &mut effective);
            }
        }
        effective
    }

    fn test_directory(name: &str) -> PathBuf {
        let sequence = CANDIDATE_SEQUENCE.fetch_add(1, Ordering::Relaxed);
        std::env::temp_dir().join(format!(
            "rmac-input-{name}-{}-{sequence}",
            std::process::id()
        ))
    }

    #[test]
    fn reads_known_values_and_explicit_false_flags() {
        let settings = effective(CONFIG).settings;
        assert_eq!(settings.keyboard.repeat_delay_ms, 450);
        assert_eq!(settings.keyboard.repeat_rate, 32);
        assert!(!settings.keyboard.numlock);
        assert!(settings.mouse.natural_scroll);
        assert_eq!(settings.mouse.accel_profile, AccelProfile::Flat);
        assert_eq!(settings.mouse.accel_speed, -0.25);
        assert!(settings.mouse.middle_emulation);
        assert!(settings.touchpad.tap_to_click);
        assert!(!settings.touchpad.disable_while_typing);
        assert!(settings.touchpad.pointer.middle_emulation);
        assert_eq!(settings.touchpad.pointer.accel_speed, 0.2);
    }

    #[test]
    fn keyboard_merges_but_pointing_sections_replace() {
        let mut effective = effective(CONFIG);
        let later = KdlDocument::parse_v1(
            r#"
input {
    keyboard { repeat-rate 40; numlock; }
    mouse { accel-speed 0.5; }
}
"#,
        )
        .unwrap();
        apply_input(
            later.get("input").unwrap().children().unwrap(),
            &mut effective,
        );
        assert_eq!(effective.settings.keyboard.repeat_delay_ms, 450);
        assert_eq!(effective.settings.keyboard.repeat_rate, 40);
        assert!(effective.settings.keyboard.numlock);
        assert_eq!(effective.settings.mouse.accel_speed, 0.5);
        assert!(!effective.settings.mouse.natural_scroll);
        assert!(!effective.settings.mouse.middle_emulation);
    }

    #[test]
    fn managed_override_preserves_unknown_pointer_nodes_and_explicit_off() {
        let effective = effective(CONFIG);
        let authority = Authority {
            main_path: PathBuf::from("/config.kdl"),
            main_source: String::new(),
            managed_path: PathBuf::from("/.rmac-input.kdl"),
            managed_source: None,
            has_managed_include: false,
            safe_to_write: true,
            detail: None,
            effective: effective.clone(),
            files: vec![ConfigFile {
                path: PathBuf::from("/config.kdl"),
                source: String::new(),
            }],
            missing_optional_files: Vec::new(),
        };
        let mut requested = effective.settings.clone();
        requested.keyboard.repeat_rate = 40;
        requested.mouse.natural_scroll = false;
        let managed = update_managed_source(&authority, &requested).unwrap();
        assert!(managed.contains("scroll-method \"on-button-down\""));
        assert!(managed.contains("accel-profile \"flat\""));
        assert!(managed.contains("numlock false"));
        assert!(!managed.contains("#false"));

        let managed =
            parse_managed_document(&managed).unwrap_or_else(|error| panic!("{error}\n{managed}"));
        let mut reread = effective;
        apply_input(
            managed.get("input").unwrap().children().unwrap(),
            &mut reread,
        );
        assert_eq!(reread.settings, requested);
    }

    #[test]
    fn include_graph_is_recursive_positional_and_bounded() {
        let directory = test_directory("includes");
        std::fs::create_dir_all(&directory).unwrap();
        std::fs::write(
            directory.join("base.kdl"),
            "input {\n    keyboard {\n        repeat-delay 300\n        numlock\n    }\n    mouse {\n        natural-scroll\n    }\n}\n",
        )
        .unwrap();
        std::fs::write(
            directory.join("nested.kdl"),
            "include \"base.kdl\"\ninput {\n    keyboard {\n        repeat-rate 40\n        numlock false\n    }\n    mouse {\n        accel-speed 0.5\n    }\n}\n",
        )
        .unwrap();
        std::fs::write(
            directory.join("config.kdl"),
            "include optional=true \"missing.kdl\"\ninclude \"nested.kdl\"\n",
        )
        .unwrap();
        let mut graph = GraphState::default();
        traverse_config(&directory.join("config.kdl"), 0, &mut graph).unwrap();
        assert_eq!(graph.files.len(), 3);
        assert_eq!(graph.effective.settings.keyboard.repeat_delay_ms, 300);
        assert_eq!(graph.effective.settings.keyboard.repeat_rate, 40);
        assert!(!graph.effective.settings.keyboard.numlock);
        assert_eq!(graph.effective.settings.mouse.accel_speed, 0.5);
        assert!(!graph.effective.settings.mouse.natural_scroll);
        std::fs::remove_dir_all(directory).unwrap();
    }

    #[test]
    fn recursive_include_is_rejected() {
        let directory = test_directory("cycle");
        std::fs::create_dir_all(&directory).unwrap();
        std::fs::write(directory.join("a.kdl"), "include \"b.kdl\"\n").unwrap();
        std::fs::write(directory.join("b.kdl"), "include \"a.kdl\"\n").unwrap();
        let mut graph = GraphState::default();
        assert!(traverse_config(&directory.join("a.kdl"), 0, &mut graph).is_err());
        std::fs::remove_dir_all(directory).unwrap();
    }

    #[test]
    fn empty_xkb_follows_localed_but_explicit_empty_options_do_not() {
        let empty = effective("input { keyboard { xkb {}; }; }\n");
        assert!(empty.settings.keyboard.xkb_override.is_none());
        let explicit = effective(
            r#"
input {
    keyboard {
        xkb {
            options ""
        }
    }
}
"#,
        );
        assert_eq!(
            explicit.settings.keyboard.xkb_override.unwrap().options,
            Some(String::new())
        );
    }

    #[test]
    fn rejects_out_of_range_values() {
        let mut settings = InputSettings::default();
        settings.mouse.accel_speed = 1.1;
        assert!(validate_settings(&settings).is_err());
        settings.mouse.accel_speed = 0.0;
        settings.keyboard.repeat_rate = 0;
        assert!(validate_settings(&settings).is_err());
    }

    #[test]
    fn managed_file_rejects_unrelated_top_level_content() {
        let foreign = format!("{MANAGED_HEADER}\nspawn \"private-command\"\n");
        assert!(parse_managed_document(&foreign).is_err());
        let duplicate = format!("{MANAGED_HEADER}\ninput {{ keyboard {{}}; keyboard {{}}; }}\n");
        assert!(parse_managed_document(&duplicate).is_err());
        let unsupported_keyboard =
            format!("{MANAGED_HEADER}\ninput {{ keyboard {{ xkb {{}}; }}; }}\n");
        assert!(parse_managed_document(&unsupported_keyboard).is_err());
        let imitated_header = format!("{MANAGED_HEADER} but not really\n");
        assert!(parse_managed_document(&imitated_header).is_err());
    }

    #[test]
    fn include_nodes_reject_children_and_track_missing_optional_files() {
        let source = Path::new("/config/config.kdl");
        let document = KdlDocument::parse_v1("include \"child.kdl\" { input {}; }\n").unwrap();
        assert!(include_path(&document.nodes()[0], source).is_err());

        let directory = test_directory("optional");
        std::fs::create_dir_all(&directory).unwrap();
        std::fs::write(
            directory.join("config.kdl"),
            "include optional=true \"missing.kdl\"\n",
        )
        .unwrap();
        let mut graph = GraphState::default();
        traverse_config(&directory.join("config.kdl"), 0, &mut graph).unwrap();
        assert_eq!(graph.missing_optional_files.len(), 1);
        assert_eq!(
            graph.missing_optional_files[0],
            directory.join("missing.kdl")
        );
        std::fs::remove_dir_all(directory).unwrap();
    }

    #[test]
    fn concurrent_include_changes_are_rejected_before_save() {
        let directory = test_directory("concurrency");
        std::fs::create_dir_all(&directory).unwrap();
        let main_path = directory.join("config.kdl");
        let included_path = directory.join("included.kdl");
        let main_source = "include \"included.kdl\"\n";
        let included_source = "input { keyboard { repeat-rate 30; }; }\n";
        std::fs::write(&main_path, main_source).unwrap();
        std::fs::write(&included_path, included_source).unwrap();
        let authority = Authority {
            main_path: main_path.clone(),
            main_source: main_source.into(),
            managed_path: directory.join(MANAGED_CONFIG_NAME),
            managed_source: None,
            has_managed_include: false,
            safe_to_write: true,
            detail: None,
            effective: EffectiveConfig::default(),
            files: vec![
                ConfigFile {
                    path: main_path,
                    source: main_source.into(),
                },
                ConfigFile {
                    path: included_path.clone(),
                    source: included_source.into(),
                },
            ],
            missing_optional_files: Vec::new(),
        };
        assert!(ensure_authority_unchanged(&authority).is_ok());
        std::fs::write(&included_path, "input { keyboard { repeat-rate 31; }; }\n").unwrap();
        assert!(ensure_authority_unchanged(&authority).is_err());
        std::fs::remove_dir_all(directory).unwrap();
    }

    #[test]
    fn managed_include_requires_one_exact_final_main_reference() {
        let directory = test_directory("managed-include");
        std::fs::create_dir_all(&directory).unwrap();
        let main_path = directory.join("config.kdl");
        let managed_path = directory.join(MANAGED_CONFIG_NAME);
        std::fs::write(
            &managed_path,
            format!("{MANAGED_HEADER}\ninput {{ keyboard {{ repeat-rate 30; }}; }}\n"),
        )
        .unwrap();
        let location = ConfigLocation {
            path: main_path.clone(),
            writable_user_config: true,
        };

        std::fs::write(&main_path, "include \"./.rmac-input.kdl\"\n").unwrap();
        let aliased = load_authority(&location).unwrap();
        assert!(!aliased.safe_to_write);

        std::fs::write(&main_path, "include \".rmac-input.kdl\"\n").unwrap();
        let exact = load_authority(&location).unwrap();
        assert!(exact.safe_to_write);
        assert!(exact.has_managed_include);
        std::fs::remove_dir_all(directory).unwrap();
    }

    #[test]
    fn helper_output_is_drained_without_unbounded_retention() {
        let (captured, truncated) = drain_bounded(std::io::Cursor::new(vec![b'x'; 32]), 8).unwrap();
        assert_eq!(captured, vec![b'x'; 8]);
        assert!(truncated);
    }

    #[test]
    fn device_classification_prefers_udev_capabilities_without_serial_data() {
        assert_eq!(
            classify_device("Generic Device", "E:ID_INPUT=1\nE:ID_INPUT_TOUCHPAD=1\n"),
            DeviceKind::Touchpad
        );
        assert_eq!(classify_device("USB Keyboard", ""), DeviceKind::Keyboard);
        assert_eq!(
            classify_device("Unknown", "E:ID_INPUT_MOUSE=1\n"),
            DeviceKind::Mouse
        );
    }

    #[test]
    fn config_reload_events_require_an_explicit_success_state() {
        assert_eq!(
            config_load_failed(&serde_json::json!({"ConfigLoaded": {"failed": false}})),
            Some(false)
        );
        assert_eq!(
            config_load_failed(&serde_json::json!({"ConfigLoaded": {"failed": true}})),
            Some(true)
        );
        assert_eq!(
            config_load_failed(&serde_json::json!({"ConfigLoaded": {}})),
            None
        );
    }

    #[cfg(unix)]
    #[test]
    fn reload_witness_reads_bounded_success_and_failure_events() {
        let (client, mut server) = std::os::unix::net::UnixStream::pair().unwrap();
        server
            .write_all(
                b"{\"Ok\":\"Handled\"}\n{\"ConfigLoaded\":{\"failed\":false}}\n{\"ConfigLoaded\":{\"failed\":true}}\n",
            )
            .unwrap();
        let mut reader = std::io::BufReader::new(client);
        let deadline = std::time::Instant::now() + std::time::Duration::from_secs(1);
        assert!(read_reload_json_line(&mut reader, deadline)
            .unwrap()
            .get("Ok")
            .is_some());
        assert!(!next_config_load(&mut reader, deadline).unwrap());
        assert!(next_config_load(&mut reader, deadline).unwrap());
    }
}
