//! Persistent keyboard, mouse, and touchpad settings for a niri session.
//!
//! The service traverses niri's positional include graph and owns only one
//! final managed include. A same-directory candidate is validated by niri
//! before either live file changes; niri then applies the change through config
//! hot reload.

use kdl::{KdlDocument, KdlNode, KdlValue};
use std::collections::HashSet;
use std::io::Read as _;
#[cfg(unix)]
use std::io::{BufRead as _, Write as _};
use std::path::{Path, PathBuf};
use std::process::{Command, ExitStatus, Stdio};
use std::sync::atomic::{AtomicU64, Ordering};

mod config;
mod model;
mod persistence;
#[cfg(test)]
mod tests;

use config::*;
pub use model::*;
use persistence::*;

static CANDIDATE_SEQUENCE: AtomicU64 = AtomicU64::new(0);
const MANAGED_CONFIG_NAME: &str = ".rmac-input.kdl";
const MANAGED_HEADER: &str = "// Managed by rmac System Settings. Do not edit this file by hand.";
const MAX_INCLUDE_DEPTH: usize = 10;
const MAX_CONFIG_FILES: usize = 64;
const MAX_CONFIG_BYTES: u64 = 2 * 1024 * 1024;
const MAX_GRAPH_BYTES: u64 = 8 * 1024 * 1024;
const MAX_COMMAND_OUTPUT_BYTES: usize = 4 * 1024 * 1024;
const COMMAND_TIMEOUT: std::time::Duration = std::time::Duration::from_secs(10);
#[cfg(unix)]
const RELOAD_TIMEOUT: std::time::Duration = std::time::Duration::from_secs(3);

/// Read effective values after recursively applying niri's positional include
/// graph and its non-merging pointing-device sections.
pub fn snapshot() -> Result<Snapshot, Error> {
    let Some(location) = config_path()? else {
        let (devices, device_detail) = system_devices();
        return Ok(Snapshot {
            detail: Some("No existing niri configuration was found.".into()),
            devices,
            device_detail,
            ..Snapshot::default()
        });
    };
    let available = niri_available();
    if available {
        validate_current_config(&location.path)?;
    }
    let authority = load_authority(&location)?;
    Ok(snapshot_from_authority(authority, available))
}

/// Validate and persist all supported input settings as one transaction.
pub fn save(settings: &InputSettings) -> Result<Snapshot, Error> {
    validate_settings(settings)?;
    let Some(location) = config_path()? else {
        return Err(Error::new(
            "save input settings",
            "no existing niri configuration was found",
        ));
    };
    let authority = load_authority(&location)?;
    let available = niri_available();
    if !available {
        return Err(Error::new(
            "save input settings",
            "input controls require the niri compositor on Linux",
        ));
    }
    if !authority.safe_to_write {
        return Err(Error::new(
            "save input settings",
            authority.detail.unwrap_or_else(|| {
                "input configuration requires a writable user niri configuration".into()
            }),
        ));
    }
    save_with_authority(authority, settings)
}

/// Watch Linux input hotplug. Niri `ConfigLoaded` remains the authoritative
/// refresh hint for changes anywhere in the configuration include graph.
pub async fn watch(sender: async_channel::Sender<WatchEvent>) -> Result<(), Error> {
    system_watch(sender).await
}
