[package]
name = "rmac-mail-imap"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
publish = false

[dependencies]
base64 = "0.22"
imap-codec = "=1.0.0"
rustls = { version = "0.23", default-features = false, features = ["ring", "std", "tls12"] }
rustls-native-certs = "0.8"
zeroize.workspace = true
