[package]
name = "rmac-notes-storage"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
publish = false

[dependencies]
image = { workspace = true, features = ["jpeg", "png", "webp"] }
libc.workspace = true
rmac-notes-store.workspace = true
rmac-storage.workspace = true
sha2.workspace = true
