[package]
name = "rmac-shortcuts"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
publish = false

[dependencies]
async-channel.workspace = true
async-io.workspace = true
futures-util.workspace = true
rmac-storage.workspace = true
serde.workspace = true
serde_json.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
ashpd.workspace = true
blocking.workspace = true
libc.workspace = true
rmac-dbus.workspace = true
zbus.workspace = true

[[bin]]
name = "rmac-shortcut-broker"
path = "src/bin/broker.rs"

[[bin]]
name = "rmac-shortcut-dispatch"
path = "src/bin/dispatch.rs"

[[bin]]
name = "rmac-locker"
path = "src/bin/locker.rs"

[[bin]]
name = "rmac-lock-coordinator"
path = "src/bin/lock-coordinator.rs"

[[bin]]
name = "rmac-idle-locker"
path = "src/bin/idle-locker.rs"
