[package]
name = "rmac-terminal"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[[bin]]
name = "rmac-terminal"
path = "src/main.rs"

[dependencies]
async-channel.workspace = true
gpui.workspace = true
gpui-component.workspace = true
rmac-ui.workspace = true
alacritty_terminal = "0.25"
portable-pty = "0.9"
rmac-storage.workspace = true
vte = "0.15"

[target.'cfg(unix)'.dependencies]
libc.workspace = true
