[package]
name = "rmac-wallpaper-image"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
publish = false

[dependencies]
async-channel.workspace = true
image = { workspace = true, features = ["jpeg", "png", "webp"] }
notify.workspace = true
rmac-compositor.workspace = true
rmac-shell-settings.workspace = true
rmac-wallpaper.workspace = true
rmac-wallpaper-system.workspace = true
