[package]
name = "rmac-text-editor"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[[bin]]
name = "rmac-text-editor"
path = "src/main.rs"

[dependencies]
async-channel.workspace = true
gpui.workspace = true
gpui-component.workspace = true
gpui-component-assets.workspace = true
notify.workspace = true
rmac-ui.workspace = true
rmac-editor.workspace = true
rmac-recent-documents.workspace = true
rmac-storage.workspace = true

[target.'cfg(unix)'.dependencies]
libc.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
raw-window-handle.workspace = true
rmac-print-linux.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
objc2.workspace = true
objc2-foundation = { workspace = true, features = [
    "NSAttributedString", "NSString", "NSData", "NSRange", "NSValue", "NSDictionary",
] }
objc2-app-kit = { workspace = true, features = [
    "NSAttributedString", "NSFont", "NSFontDescriptor", "NSColor", "NSColorSpace",
] }
