[package]
name = "rmac-ui"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
gpui.workspace = true
gpui-component.workspace = true
gpui-component-assets.workspace = true
async-channel.workspace = true
rmac-appearance.workspace = true
rmac-appearance-portal.workspace = true
rmac-theme.workspace = true
