[package]
name = "rmac-ui"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
gpui.workspace = true
gpui_platform.workspace = true
gpui-component.workspace = true
gpui-component-assets.workspace = true
async-channel.workspace = true
async-io.workspace = true
rmac-appearance.workspace = true
rmac-appearance-portal.workspace = true
rmac-app-menu.workspace = true
rmac-apps.workspace = true
rmac-compositor.workspace = true
rmac-compositor-niri.workspace = true
rmac-design.workspace = true
rmac-theme.workspace = true
rmac-window-state.workspace = true

[target.'cfg(unix)'.dependencies]
libc.workspace = true
