#!/usr/bin/env python3
"""Generate packaging/windows/Apps.wxs from apps.json (ADR 0023 "Installer").

One <Component> per app: its exe (the installer's own copy, built with
version info and an icon already embedded -- rmac-windows-resource-build),
a Start Menu shortcut carrying the same AppUserModelID the app sets for
itself at startup (rmac_ui::app_menu's `app_user_model_id`, kept in step
with this file's `aumid()` by a test in crates/rmac-ui/src/app_menu.rs), and,
for apps that declare file extensions, "Open with" registration under
HKCU\\Software\\Classes\\Applications -- offered, never forced as the
default handler, so a user's existing default stays untouched.

Adding an app Lulo ships on Windows: append one object to apps.json.
Nothing here, in Product.wxs, or in build-installer.sh changes.

Usage:
    python3 generate_apps_wxs.py --exe-dir <dir with the built .exe files> \
        --output Apps.wxs
"""

from __future__ import annotations

import argparse
import json
import pathlib
import sys
import xml.sax.saxutils as saxutils

WIX_NAMESPACE = "http://wixtoolset.org/schemas/v4/wxs"


def aumid(app_id: str) -> str:
    """`"org.rmac.Calculator"` -> `"Lulo.Calculator"`; must match
    `rmac_ui::app_menu::app_user_model_id` exactly (see that function's
    doc comment and its `aumid_tests`)."""
    prefix = "org.rmac."
    return "Lulo." + (app_id[len(prefix):] if app_id.startswith(prefix) else app_id)


def attr(value: str) -> str:
    return saxutils.quoteattr(value)


def component_id(app: dict) -> str:
    return "Comp_" + app["id"].replace("-", "_")


def file_id(app: dict) -> str:
    return "File_" + app["id"].replace("-", "_")


def shortcut_id(app: dict) -> str:
    return "Shortcut_" + app["id"].replace("-", "_")


def render_component(app: dict, exe_dir: pathlib.Path) -> str:
    exe_name = f"{app['bin']}.exe"
    source = (exe_dir / exe_name).as_posix()
    fid = file_id(app)
    lines = [
        f'      <Component Id={attr(component_id(app))} Directory="INSTALLFOLDER" Guid="*">',
        f'        <File Id={attr(fid)} Source={attr(source)} KeyPath="yes">',
        f'          <Shortcut Id={attr(shortcut_id(app))} Directory="LuloMenuFolder"'
        f' Name={attr(app["display_name"])} WorkingDirectory="INSTALLFOLDER" Advertise="no">',
        f'            <ShortcutProperty Key="System.AppUserModel.ID" Value={attr(aumid(app["app_id"]))} />',
        '          </Shortcut>',
        '        </File>',
    ]
    extensions = app.get("extensions") or []
    if extensions:
        app_key = "Software\\Classes\\Applications\\" + exe_name
        open_command_key = app_key + "\\shell\\open\\command"
        supported_types_key = app_key + "\\SupportedTypes"
        command = f"&quot;[#{fid}]&quot; &quot;%1&quot;"
        lines.append(
            f'        <RegistryValue Root="HKCU" Key={attr(app_key)} Name="FriendlyAppName"'
            f' Type="string" Value={attr(app["display_name"])} />'
        )
        lines.append(
            f'        <RegistryValue Root="HKCU" Key={attr(open_command_key)}'
            f' Type="string" Value="{command}" />'
        )
        for extension in extensions:
            lines.append(
                f'        <RegistryValue Root="HKCU" Key={attr(supported_types_key)}'
                f' Name={attr("." + extension)} Type="string" Value="" />'
            )
    lines.append('      </Component>')
    return "\n".join(lines)


def render(apps: list[dict], exe_dir: pathlib.Path) -> str:
    components = "\n".join(render_component(app, exe_dir) for app in apps)
    return f"""<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by packaging/windows/generate_apps_wxs.py from apps.json.
     Do not edit by hand: add an app to apps.json instead, and re-run
     build-installer.sh (or generate_apps_wxs.py directly). -->
<Wix xmlns="{WIX_NAMESPACE}">
  <Fragment>
    <ComponentGroup Id="AppComponents">
{components}
    </ComponentGroup>
  </Fragment>
</Wix>
"""


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--apps",
        default=str(pathlib.Path(__file__).with_name("apps.json")),
        help="apps.json path (default: next to this script)",
    )
    parser.add_argument("--exe-dir", required=True, help="directory holding the built .exe files")
    parser.add_argument("--output", required=True, help="where to write Apps.wxs")
    args = parser.parse_args(argv)

    apps = json.loads(pathlib.Path(args.apps).read_text())
    if not apps:
        raise SystemExit("apps.json lists no apps")
    exe_dir = pathlib.Path(args.exe_dir).resolve()
    for app in apps:
        exe = exe_dir / f"{app['bin']}.exe"
        if not exe.is_file():
            raise SystemExit(f"missing built exe for {app['id']!r}: {exe}")

    pathlib.Path(args.output).write_text(render(apps, exe_dir))
    print(f"wrote {args.output} for {len(apps)} apps")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
