//! Cross-platform display discovery and safe niri output controls.

#[cfg(any(not(target_os = "macos"), test))]
use serde::Deserialize;
#[cfg(any(not(target_os = "macos"), test))]
use std::collections::{HashMap, HashSet};
#[cfg(not(target_os = "macos"))]
use std::path::{Path, PathBuf};
use std::process::{Command, ExitStatus, Stdio};
#[cfg(not(target_os = "macos"))]
use std::sync::atomic::{AtomicU64, Ordering};

mod command;
#[cfg(any(not(target_os = "macos"), test))]
mod linux;
#[cfg(target_os = "macos")]
mod macos;
mod model;
#[cfg(test)]
mod tests;

use command::*;
#[cfg(any(not(target_os = "macos"), test))]
use linux::*;
#[cfg(target_os = "macos")]
use macos::*;
pub use model::*;

#[cfg(any(not(target_os = "macos"), test))]
use kdl::{KdlDocument, KdlNode, KdlValue};

#[cfg(any(not(target_os = "macos"), test))]
const MANAGED_CONFIG_NAME: &str = ".rmac-displays.kdl";
#[cfg(any(not(target_os = "macos"), test))]
const MANAGED_HEADER: &str = "// Managed by rmac System Settings. Do not edit this file by hand.";
#[cfg(any(not(target_os = "macos"), test))]
const MAX_OUTPUTS: usize = 32;
#[cfg(any(not(target_os = "macos"), test))]
const MAX_OUTPUT_ID_BYTES: usize = 1024;
const MAX_COMMAND_OUTPUT_BYTES: usize = 4 * 1024 * 1024;
const COMMAND_TIMEOUT: std::time::Duration = std::time::Duration::from_secs(10);
#[cfg(not(target_os = "macos"))]
const MAX_CONFIG_BYTES: u64 = 2 * 1024 * 1024;
const MAX_LAYOUT_COORDINATE: i32 = 1_000_000;
#[cfg(not(target_os = "macos"))]
static CANDIDATE_SEQUENCE: AtomicU64 = AtomicU64::new(0);

pub fn snapshot() -> Result<Snapshot, Error> {
    system_snapshot()
}

pub fn set_mode(output: &Output, mode: Mode) -> Result<AppliedChange, Error> {
    let baseline = exact_current_snapshot(output, "change display mode")?;
    let current = output_from_snapshot(&baseline, &output.id);
    if !current.modes.contains(&mode) {
        return Err(Error::new(
            "change display mode",
            "the selected mode is no longer advertised by this display",
        ));
    }
    run_niri_output(
        &output.id,
        &["mode", &mode.niri_argument()],
        "change display mode",
    )?;
    let snapshot = verify_output_change(output, "verify display mode", |current| {
        current.current_mode() == Some(mode)
    })?;
    Ok(AppliedChange { baseline, snapshot })
}

pub fn set_scale(output: &Output, scale: f64) -> Result<AppliedChange, Error> {
    if !scale.is_finite() || !(0.5..=4.0).contains(&scale) {
        return Err(Error::new("change display scale", "invalid scale"));
    }
    let baseline = exact_current_snapshot(output, "change display scale")?;
    run_niri_output(
        &output.id,
        &["scale", &format!("{scale:.2}")],
        "change display scale",
    )?;
    let snapshot = verify_output_change(output, "verify display scale", |current| {
        current
            .logical
            .as_ref()
            .is_some_and(|logical| (logical.scale - scale).abs() <= 0.001)
    })?;
    Ok(AppliedChange { baseline, snapshot })
}

pub fn set_transform(output: &Output, transform: &Transform) -> Result<AppliedChange, Error> {
    let transform = transform
        .niri_argument()
        .ok_or_else(|| Error::new("change display rotation", "unsupported transform"))?;
    let baseline = exact_current_snapshot(output, "change display rotation")?;
    run_niri_output(
        &output.id,
        &["transform", transform],
        "change display rotation",
    )?;
    let snapshot = verify_output_change(output, "verify display rotation", |current| {
        current
            .logical
            .as_ref()
            .is_some_and(|logical| logical.transform.niri_argument() == Some(transform))
    })?;
    Ok(AppliedChange { baseline, snapshot })
}

pub fn set_position(output: &Output, x: i32, y: i32) -> Result<AppliedChange, Error> {
    if x.unsigned_abs() > MAX_LAYOUT_COORDINATE as u32
        || y.unsigned_abs() > MAX_LAYOUT_COORDINATE as u32
    {
        return Err(Error::new(
            "change display position",
            "display position is outside the safe range",
        ));
    }
    let baseline = exact_current_snapshot(output, "change display position")?;
    run_niri_output(
        &output.id,
        &["position", "set", &x.to_string(), &y.to_string()],
        "change display position",
    )?;
    let snapshot = verify_output_change(output, "verify display position", |current| {
        current
            .logical
            .as_ref()
            .is_some_and(|logical| logical.x == x && logical.y == y)
    })?;
    Ok(AppliedChange { baseline, snapshot })
}

pub fn current_layout(snapshot: &Snapshot, primary: &str) -> Result<Layout, Error> {
    let outputs = snapshot
        .outputs
        .iter()
        .filter_map(|output| {
            Some(OutputConfiguration {
                id: output.id.clone(),
                mode: output.current_mode()?,
                scale: output.logical.as_ref()?.scale,
                transform: output.logical.as_ref()?.transform.clone(),
                x: output.logical.as_ref()?.x,
                y: output.logical.as_ref()?.y,
                logical_width: output.logical.as_ref()?.width,
                logical_height: output.logical.as_ref()?.height,
            })
        })
        .collect();
    let layout = Layout {
        outputs,
        primary: primary.to_owned(),
    };
    validate_layout(&layout, snapshot)?;
    Ok(layout)
}

/// Persist an already-applied complete layout after revalidating it against a
/// fresh compositor snapshot. The running compositor remains the authority for
/// what the user actually confirmed.
pub fn persist_layout(layout: &Layout) -> Result<Snapshot, Error> {
    system_persist_layout(layout)
}

/// Restore the complete enabled-output state captured before a risky display
/// mutation. Hardware identities are revalidated before any command runs.
pub fn restore_snapshot(expected: &Snapshot, owned_current: &Snapshot) -> Result<Snapshot, Error> {
    system_restore_snapshot(expected, owned_current)
}

fn exact_current_snapshot(expected: &Output, operation: &'static str) -> Result<Snapshot, Error> {
    validate_output_id(&expected.id)?;
    let snapshot = system_snapshot()?;
    if !snapshot.can_configure {
        return Err(Error::new(
            operation,
            "display configuration is unavailable in this session",
        ));
    }
    let current = snapshot
        .outputs
        .iter()
        .find(|output| output.id == expected.id)
        .ok_or_else(|| Error::new(operation, "the selected display disconnected"))?;
    if current.connector != expected.connector
        || current.serial != expected.serial
        || current.name != expected.name
    {
        return Err(Error::new(
            operation,
            "the selected display identity changed; refresh Displays before trying again",
        ));
    }
    Ok(snapshot)
}

fn output_from_snapshot<'a>(snapshot: &'a Snapshot, id: &str) -> &'a Output {
    snapshot
        .outputs
        .iter()
        .find(|output| output.id == id)
        .expect("the exact output was checked in this snapshot")
}

fn verify_output_change(
    expected: &Output,
    operation: &'static str,
    matches: impl Fn(&Output) -> bool,
) -> Result<Snapshot, Error> {
    let deadline = std::time::Instant::now() + std::time::Duration::from_secs(3);
    loop {
        match system_snapshot() {
            Ok(snapshot) => match snapshot
                .outputs
                .iter()
                .find(|output| output.id == expected.id)
            {
                Some(current)
                    if current.connector != expected.connector
                        || current.serial != expected.serial
                        || current.name != expected.name =>
                {
                    return Err(Error::new(
                        operation,
                        "the selected display identity changed during the request",
                    ));
                }
                Some(current) if matches(current) => return Ok(snapshot),
                Some(_) | None => {}
            },
            Err(error) if std::time::Instant::now() >= deadline => return Err(error),
            Err(_) => {}
        }
        if std::time::Instant::now() >= deadline {
            return Err(Error::new(
                operation,
                "niri did not confirm the requested display state within three seconds",
            ));
        }
        std::thread::sleep(std::time::Duration::from_millis(50));
    }
}
