//! One-line Windows exe resources for each Lulo app's `build.rs` (ADR 0023
//! "Installer"): a version-info block (`FileDescription`, `ProductName`
//! and `CompanyName` "Lulo", `FileVersion`/`ProductVersion` from Cargo's
//! own `CARGO_PKG_VERSION`) and, once the icon-conversion step has run, the
//! exe's own icon.
//!
//! Icons come from `packaging/windows/icons/<icon_id>.ico`, which
//! `scripts/windows/make_icons.sh` rasterises at build time from this
//! repo's own artwork (`packaging/rmac-apps/icons/org.rmac.<App>.svg`,
//! itself generated by `scripts/build-icons.py`) -- never Apple's. A build
//! that has not run that step yet (a plain local `cargo build`) still
//! succeeds: the exe gets correct version info and falls back to the
//! platform's default binary icon, with a `cargo:warning` naming why.
//!
//! Call this from a `build.rs` that does nothing else:
//!
//! ```ignore
//! fn main() {
//!     #[cfg(windows)]
//!     rmac_windows_resource_build::embed("Calculator", "calculator");
//! }
//! ```

use std::path::{Path, PathBuf};

/// `display_name` is the app's name as users see it ("Calculator", "Text
/// Editor", ...), used for the exe's `FileDescription`. `icon_id` is the
/// short id `packaging/windows/apps.json` and `scripts/windows/
/// make_icons.sh` use for this app ("calculator", "text-editor", ...),
/// used only to find `packaging/windows/icons/<icon_id>.ico`.
pub fn embed(display_name: &str, icon_id: &str) {
    let mut resource = winres::WindowsResource::new();
    resource.set("ProductName", "Lulo");
    resource.set("CompanyName", "Lulo");
    resource.set("FileDescription", display_name);
    resource.set("LegalCopyright", "Copyright the Lulo contributors");

    let full_version = std::env::var("CARGO_PKG_VERSION").unwrap_or_default();
    resource.set("ProductVersion", &full_version);
    resource.set("FileVersion", &full_version);
    let packed = pack_numeric_version(&full_version);
    resource.set_version_info(winres::VersionInfo::FILEVERSION, packed);
    resource.set_version_info(winres::VersionInfo::PRODUCTVERSION, packed);

    let icon = icon_path(icon_id);
    if icon.is_file() {
        resource.set_icon(&icon.to_string_lossy());
    } else {
        println!(
            "cargo:warning={icon_id}: no Windows icon at {}; run \
             scripts/windows/make_icons.sh first for a real one (the exe \
             still gets Lulo's version info)",
            icon.display(),
        );
    }

    if let Err(error) = resource.compile() {
        println!("cargo:warning={icon_id}: could not embed Windows resources: {error}");
    }
}

/// `"0.9.0-beta.1"` packs as `0.9.0.0`: Win32's `VS_FIXEDFILEINFO` has no
/// room for a pre-release tag, so the free-text `FileVersion`/
/// `ProductVersion` strings above carry the exact Cargo version instead.
fn pack_numeric_version(version: &str) -> u64 {
    let numeric = version.split(['-', '+']).next().unwrap_or(version);
    let mut parts = numeric
        .split('.')
        .map(|part| part.parse::<u64>().unwrap_or(0));
    let major = parts.next().unwrap_or(0);
    let minor = parts.next().unwrap_or(0);
    let patch = parts.next().unwrap_or(0);
    (major << 48) | (minor << 32) | (patch << 16)
}

fn icon_path(icon_id: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join(format!("../../packaging/windows/icons/{icon_id}.ico"))
}

#[cfg(test)]
mod tests {
    use super::pack_numeric_version;

    #[test]
    fn packs_a_prerelease_version_as_its_numeric_prefix() {
        assert_eq!(pack_numeric_version("0.9.0-beta.1"), 9u64 << 32);
        assert_eq!(
            pack_numeric_version("1.2.3"),
            (1u64 << 48) | (2u64 << 32) | (3u64 << 16)
        );
        assert_eq!(pack_numeric_version("2.0.0+build"), 2u64 << 48);
    }
}
