[package]
name = "rmac-search"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
chrono.workspace = true
libc.workspace = true
quick-xml.workspace = true
rmac-recent-documents.workspace = true
url.workspace = true
walkdir.workspace = true
