[package]
name = "rmac-accounts-linux"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
publish = false

[dependencies]
rmac-accounts.workspace = true
rmac-portal.workspace = true
url.workspace = true
sha2.workspace = true
serde_json.workspace = true
ureq.workspace = true
base64 = "0.22"

[target.'cfg(target_os = "linux")'.dependencies]
zbus.workspace = true
libc.workspace = true
