[package]
name = "rmac-appearance-portal"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
async-channel.workspace = true
rmac-appearance.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
ashpd.workspace = true
async-io.workspace = true
futures-util.workspace = true
