[package]
name = "rmac-sound"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[[bin]]
name = "rmac-sound"
path = "src/bin/sound.rs"

[dependencies]
rmac-audio.workspace = true
rmac-focus-linux.workspace = true
rmac-storage.workspace = true
serde.workspace = true
serde_json.workspace = true
