[package]
name = "rmac-system-settings"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[[bin]]
name = "rmac-system-settings"
path = "src/main.rs"

[dependencies]
gpui.workspace = true
gpui-component.workspace = true
gpui-component-assets.workspace = true
rmac-audio.workspace = true
rmac-bluetooth.workspace = true
rmac-network.workspace = true
rmac-power.workspace = true
rmac-storage.workspace = true
rmac-ui.workspace = true
rust-embed.workspace = true
