[package]
name = "rmac-system-settings"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[[bin]]
name = "rmac-system-settings"
path = "src/main.rs"

[dependencies]
async-channel.workspace = true
gpui.workspace = true
gpui-component.workspace = true
gpui-component-assets.workspace = true
rmac-audio.workspace = true
rmac-appearance.workspace = true
rmac-appearance-portal.workspace = true
rmac-apps.workspace = true
rmac-bluetooth.workspace = true
rmac-display.workspace = true
rmac-focus.workspace = true
rmac-focus-linux.workspace = true
rmac-focus-settings.workspace = true
rmac-input.workspace = true
rmac-mounts.workspace = true
rmac-network.workspace = true
rmac-notifications-linux.workspace = true
rmac-notifications.workspace = true
rmac-notifications-store.workspace = true
rmac-power.workspace = true
rmac-shortcuts.workspace = true
rmac-system-info.workspace = true
rmac-theme.workspace = true
rmac-ui.workspace = true
rmac-updates.workspace = true
rmac-updates-linux.workspace = true
rust-embed.workspace = true
