[package]
name = "rmac-finder"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[[bin]]
name = "rmac-finder"
path = "src/main.rs"

[dependencies]
async-channel.workspace = true
gpui.workspace = true
gpui-component.workspace = true
gpui-component-assets.workspace = true
rmac-ui.workspace = true
chrono.workspace = true
rust-embed.workspace = true
trash = "5"
notify = "7"

[target.'cfg(target_os = "macos")'.dependencies]
objc2.workspace = true
objc2-foundation = { workspace = true, features = ["NSArray", "NSString", "NSURL"] }
objc2-app-kit = { workspace = true, features = ["NSPasteboard"] }
