[package]
name = "rmac-notes"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[[bin]]
name = "rmac-notes"
path = "src/main.rs"

[dependencies]
async-channel.workspace = true
gpui.workspace = true
gpui-component.workspace = true
image.workspace = true
rmac-ui.workspace = true
rmac-editor.workspace = true
rmac-notes-runtime.workspace = true
rmac-notes-storage.workspace = true
rmac-notes-store.workspace = true
rmac-portal.workspace = true
rmac-print.workspace = true
rmac-storage.workspace = true
chrono.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
raw-window-handle.workspace = true
rmac-print-linux.workspace = true
