[package]
name = "rmac-compositor-niri"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
publish = false

[dependencies]
async-channel.workspace = true
async-io.workspace = true
futures-util.workspace = true
rmac-compositor.workspace = true
serde.workspace = true
serde_json.workspace = true
