[package]
name = "rmac-notifications-linux"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
publish = false

[dependencies]
async-channel.workspace = true
async-io.workspace = true
blocking.workspace = true
futures-util.workspace = true
image = { workspace = true, features = ["jpeg", "png"] }
libc.workspace = true
quick-xml.workspace = true
rmac-appearance.workspace = true
rmac-apps.workspace = true
rmac-audio.workspace = true
rmac-compositor.workspace = true
rmac-focus-linux.workspace = true
rmac-icon.workspace = true
rmac-notifications.workspace = true
rmac-notifications-runtime.workspace = true
rmac-notifications-store.workspace = true
rmac-shell-invocation.workspace = true
zbus.workspace = true
