[package]
name = "rmac-lock-provider-linux"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
publish = false

[features]
provider = ["dep:zbus"]
development-provider = ["provider"]

[dependencies]
chrono.workspace = true
rmac-lock-provider.workspace = true
zeroize.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
cosmic-text.workspace = true
libc.workspace = true
pam-sys2.workspace = true
rustix.workspace = true
wayland-client.workspace = true
wayland-protocols.workspace = true
xkbcommon.workspace = true
zbus = { workspace = true, optional = true }

[[bin]]
name = "rmac-lock-provider"
path = "src/bin/provider.rs"
required-features = ["provider"]
