[package]
name = "rmac-lock-provider-linux"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
publish = false

[dependencies]
rmac-lock-provider.workspace = true
zeroize.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
rustix.workspace = true
wayland-client.workspace = true
wayland-protocols.workspace = true
