//! Complete System Settings session-state schema.

use super::*;
pub(super) struct Settings {
    pub(super) system_data_loading: bool,
    pub(super) system_data_busy: bool,
    pub(super) system_data_error: Option<SharedString>,
    pub(super) system_data_stream_error: Option<SharedString>,
    pub(super) system_data_generation: u64,
    pub(super) system_data_refresh_pending: bool,
    pub(super) system_data_stream_refreshing: bool,
    pub(super) hostname_editor: Option<Entity<InputState>>,
    pub(super) diagnostics_copied: bool,
    pub(super) account: SharedString,
    pub(super) sysinfo: rmac_system_info::Snapshot,
    pub(super) screen_reader: ScreenReaderCapability,
    pub(super) screen_reader_loading: bool,
    pub(super) updates_loading: bool,
    pub(super) updates_busy: bool,
    pub(super) updates_error: Option<SharedString>,
    pub(super) updates_stream_error: Option<SharedString>,
    pub(super) updates_generation: u64,
    pub(super) updates_refresh_pending: bool,
    pub(super) updates_stream_refreshing: bool,
    pub(super) updates_preparing: bool,
    pub(super) updates_installing: bool,
    pub(super) updates_cancellation: Option<rmac_updates::Cancellation>,
    pub(super) updates_plan: Option<rmac_updates::InstallPlan>,
    pub(super) updates_progress: Option<rmac_updates::InstallProgress>,
    pub(super) updates_result: Option<rmac_updates::InstallResult>,
    pub(super) updates: Option<rmac_updates::Snapshot>,
    pub(super) time_loading: bool,
    pub(super) time_busy: bool,
    pub(super) time_error: Option<SharedString>,
    pub(super) time_stream_error: Option<SharedString>,
    pub(super) time_generation: u64,
    pub(super) time_refresh_pending: bool,
    pub(super) time_stream_refreshing: bool,
    pub(super) clock_editor: Option<Entity<InputState>>,
    pub(super) clock_confirmation: Option<rmac_time::ClockTarget>,
    pub(super) clock_setting: bool,
    pub(super) time: Option<rmac_time::Snapshot>,
    pub(super) timezone_editor: Option<Entity<InputState>>,
    pub(super) locale_loading: bool,
    pub(super) locale_busy: bool,
    pub(super) locale_error: Option<SharedString>,
    pub(super) locale_stream_error: Option<SharedString>,
    pub(super) locale_generation: u64,
    pub(super) locale_refresh_pending: bool,
    pub(super) locale_stream_refreshing: bool,
    pub(super) locale: Option<rmac_locale::Snapshot>,
    pub(super) locale_editor: Option<Entity<InputState>>,
    pub(super) region_editor: Option<Entity<InputState>>,
    pub(super) locale_revert: Option<rmac_locale::LocaleRollback>,
    pub(super) x11_layout_editor: Option<Entity<InputState>>,
    pub(super) x11_variant_editor: Option<Entity<InputState>>,
    pub(super) x11_options_editor: Option<Entity<InputState>>,
    pub(super) x11_keyboard_revert: Option<rmac_locale::KeyboardRollback>,
    pub(super) login_items_loading: bool,
    pub(super) login_item_busy: Option<String>,
    pub(super) login_items_error: Option<SharedString>,
    pub(super) login_items_stream_error: Option<SharedString>,
    pub(super) login_items_generation: u64,
    pub(super) login_items_refresh_pending: bool,
    pub(super) login_items_stream_refreshing: bool,
    pub(super) login_items: Option<rmac_login_items::Snapshot>,
    pub(super) login_item_add: Option<rmac_login_items::AddPreview>,
    pub(super) login_item_remove: Option<rmac_login_items::RemovePreview>,
    pub(super) sharing_loading: bool,
    pub(super) sharing_busy: bool,
    pub(super) sharing_error: Option<SharedString>,
    pub(super) sharing_stream_error: Option<SharedString>,
    pub(super) sharing: Option<rmac_sharing::Snapshot>,
    pub(super) sharing_confirmation: Option<bool>,
    pub(super) file_sharing_confirmation: Option<bool>,
    pub(super) power: rmac_power::Snapshot,
    pub(super) display: rmac_display::Snapshot,
    pub(super) network: rmac_network::NetworkSnapshot,
    pub(super) storage: Vec<rmac_mounts::Volume>,
    pub(super) storage_busy: bool,
    pub(super) storage_error: Option<SharedString>,
    pub(super) storage_stream_error: Option<SharedString>,
    pub(super) storage_generation: u64,
    pub(super) storage_refresh_pending: bool,
    pub(super) storage_stream_refreshing: bool,
    pub(super) storage_action_busy: Option<String>,
    pub(super) audio: rmac_audio::Snapshot,
    pub(super) input: rmac_input::Snapshot,
    pub(super) gtk_text: Option<rmac_gtk_settings::Snapshot>,
    pub(super) privacy: Option<rmac_privacy::Snapshot>,
    pub(super) security_coverage: Option<rmac_privacy::SecurityCoverageSnapshot>,
    pub(super) sections: Vec<Vec<Category>>,
    pub(super) selected: (usize, usize),
    pub(super) navigation_persistence: NavigationPersistence,
    pub(super) nav: Vec<SubPage>,
    /// Subpages popped by Back, replayed by Forward; cleared by any new
    /// navigation, as in the Mac toolbar.
    pub(super) forward: Vec<SubPage>,
    /// The sidebar last took a click, so its selection draws in the accent
    /// (grey once the detail is used or the window is not key).
    pub(super) sidebar_focused: bool,
    pub(super) search: Entity<InputState>,
    pub(super) search_selection: usize,
    pub(super) compact_sidebar_open: bool,
    /// Trackpad's selected tab (Point & Click, Scroll & Zoom).
    pub(super) trackpad_tab: usize,
    /// Storage categories measured on the home volume.
    pub(super) storage_categories: Option<crate::storage_categories::Categories>,
    pub(super) storage_categories_busy: bool,
    /// The Keyboard Shortcuts sheet and its selected category.
    pub(super) keyboard_shortcuts_open: bool,
    pub(super) keyboard_shortcuts_category: usize,
    pub(super) focus: FocusHandle,
    pub(super) native_window_title: String,
    pub(super) focused_once: bool,
    pub(super) wifi_error: Option<SharedString>,
    pub(super) wifi_stream_error: Option<SharedString>,
    pub(super) bluetooth_error: Option<SharedString>,
    pub(super) bluetooth_stream_error: Option<SharedString>,
    pub(super) network_error: Option<SharedString>,
    pub(super) network_stream_error: Option<SharedString>,
    pub(super) vpn_error: Option<SharedString>,
    pub(super) vpn_stream_error: Option<SharedString>,
    pub(super) audio_error: Option<SharedString>,
    pub(super) audio_stream_error: Option<SharedString>,
    pub(super) power_error: Option<SharedString>,
    pub(super) power_stream_error: Option<SharedString>,
    pub(super) display_error: Option<SharedString>,
    pub(super) input_error: Option<SharedString>,
    pub(super) input_stream_error: Option<SharedString>,
    pub(super) theme_error: Option<SharedString>,
    pub(super) theme_store_stream_error: Option<SharedString>,
    pub(super) theme_portal_stream_error: Option<SharedString>,
    pub(super) shell_settings_error: Option<SharedString>,
    pub(super) shell_settings_stream_error: Option<SharedString>,
    pub(super) gtk_text_error: Option<SharedString>,
    pub(super) gtk_text_stream_error: Option<SharedString>,
    pub(super) privacy_error: Option<SharedString>,
    pub(super) privacy_stream_error: Option<SharedString>,
    pub(super) notification_error: Option<SharedString>,
    pub(super) notification_stream_error: Option<SharedString>,

    // Notifications
    pub(super) notifications_loading: bool,
    pub(super) notification_busy: Option<String>,
    pub(super) notification_apps: Vec<rmac_notifications_linux::center::ApplicationPolicy>,
    pub(super) app_catalog: Vec<rmac_apps::Application>,
    pub(super) _app_catalog_watcher: Option<rmac_apps::CatalogWatcher>,

    // Focus
    pub(super) focus_policy_loading: bool,
    pub(super) focus_policy_busy: bool,
    pub(super) focus_policy_error: Option<SharedString>,
    pub(super) focus_policy_stream_error: Option<SharedString>,
    pub(super) focus_policy_config: Option<rmac_focus::Config>,
    pub(super) focus_policy_state: Option<rmac_focus_linux::client::Snapshot>,

    // Lock Screen
    pub(super) lock_policy_loading: bool,
    pub(super) lock_policy_busy: bool,
    pub(super) lock_policy_error: Option<SharedString>,
    pub(super) lock_policy_stream_error: Option<SharedString>,
    pub(super) lock_policy: Option<rmac_shortcuts::lock_settings::Snapshot>,
    pub(super) lock_request_busy: bool,
    pub(super) lock_request_error: Option<SharedString>,

    // Desktop & Dock
    pub(super) shell_settings_loading: bool,
    pub(super) shell_settings_busy: bool,
    pub(super) shell_settings: Option<rmac_shell_settings::Snapshot>,
    pub(super) shell_settings_revert: Option<rmac_shell_settings::DockSettings>,
    pub(super) dock_compositor: rmac_compositor::State,
    pub(super) wallpaper_target: WallpaperTarget,
    pub(super) wallpaper_revert: Option<rmac_shell_settings::WallpaperSettings>,
    pub(super) wallpaper_error: Option<SharedString>,
    pub(super) wallpaper_preview: Option<std::sync::Arc<gpui::RenderImage>>,
    pub(super) wallpaper_preview_loading: bool,
    pub(super) wallpaper_preview_error: Option<SharedString>,
    pub(super) wallpaper_preview_watch_error: Option<SharedString>,
    pub(super) wallpaper_preview_generation: u64,
    pub(super) _wallpaper_preview_watcher: Option<rmac_wallpaper_image::FileWatcher>,
    pub(super) spotlight_revert: Option<SpotlightAuthority>,
    pub(super) spotlight_error: Option<SharedString>,
    pub(super) recent_history_confirmation: bool,
    pub(super) recent_history_busy: bool,
    pub(super) recent_history_notice: Option<SharedString>,
    pub(super) shortcut_status_loading: bool,
    pub(super) shortcut_status: Option<rmac_shortcuts::BackendStatus>,
    pub(super) shortcut_status_error: Option<SharedString>,
    pub(super) shortcut_configuration_busy: bool,
    pub(super) shortcut_configuration_error: Option<SharedString>,

    // Network
    pub(super) network_loading: bool,
    pub(super) network_busy: bool,
    pub(super) network_generation: u64,
    pub(super) network_editor: Option<NetworkEditorState>,

    // VPN
    pub(super) vpn: rmac_network::VpnSnapshot,
    pub(super) vpn_loading: bool,
    pub(super) vpn_refreshing: bool,
    pub(super) vpn_busy: Option<rmac_network::VpnProfileId>,
    pub(super) vpn_cancellation: Option<rmac_network::VpnCancellation>,
    pub(super) vpn_generation: u64,
    pub(super) vpn_import_capabilities: rmac_network::VpnImportCapabilities,
    pub(super) vpn_import_loading: bool,
    pub(super) vpn_import_busy: bool,
    pub(super) vpn_import_preview: Option<rmac_network::VpnImportPreview>,
    pub(super) vpn_editor_loading: Option<rmac_network::VpnProfileId>,
    pub(super) vpn_editor_busy: bool,
    pub(super) vpn_editor: Option<VpnEditorState>,
    pub(super) vpn_secret_preparing: bool,
    pub(super) vpn_secret_busy: bool,
    pub(super) vpn_secret_preview: Option<rmac_network::VpnSecretClearPreview>,
    pub(super) vpn_delete_preparing: Option<rmac_network::VpnProfileId>,
    pub(super) vpn_delete_busy: bool,
    pub(super) vpn_delete_preview: Option<rmac_network::VpnDeletePreview>,

    // Wi-Fi
    pub(super) wifi_available: bool,
    pub(super) wifi_loading: bool,
    pub(super) wifi_busy: bool,
    pub(super) wifi_generation: u64,
    pub(super) wifi_connecting: Option<rmac_network::WifiNetworkId>,
    pub(super) wifi_forgetting: Option<rmac_network::WifiNetworkId>,
    pub(super) wifi_forget_confirmation: Option<WifiForgetPrompt>,
    pub(super) wifi_password_prompt: Option<WifiPasswordPrompt>,
    pub(super) wifi_enterprise_prompt: Option<WifiEnterprisePrompt>,
    pub(super) wifi_cancellation: Option<rmac_network::WifiCancellation>,
    pub(super) wifi_on: bool,
    pub(super) wifi_interface: Option<String>,
    pub(super) wifi_networks: Vec<rmac_network::WifiNetwork>,
    pub(super) wifi_saved_networks: Vec<rmac_network::WifiSavedNetwork>,

    // Bluetooth
    pub(super) bluetooth_available: bool,
    pub(super) bluetooth_loading: bool,
    pub(super) bluetooth_busy: bool,
    pub(super) bluetooth_generation: u64,
    pub(super) bluetooth_discovering: bool,
    pub(super) bluetooth_adapter_name: Option<String>,
    pub(super) bluetooth_on: bool,
    pub(super) bt_discoverable: bool,
    pub(super) bt_devices: Vec<rmac_bluetooth::Device>,
    pub(super) bluetooth_pairing: Option<BluetoothPairingState>,
    pub(super) bluetooth_forget_confirmation: Option<BluetoothForgetPrompt>,
    pub(super) bluetooth_forgetting: Option<String>,

    // Appearance
    pub(super) host_appearance: rmac_appearance::Snapshot,
    pub(super) theme: Option<rmac_theme::Snapshot>,
    pub(super) theme_loading: bool,
    pub(super) theme_busy: bool,
    pub(super) theme_generation: u64,
    pub(super) theme_refresh_pending: bool,
    pub(super) theme_stream_refreshing: bool,

    // External GTK application text
    pub(super) gtk_text_loading: bool,
    pub(super) gtk_text_busy: bool,
    pub(super) gtk_text_generation: u64,
    pub(super) gtk_text_refresh_pending: bool,
    pub(super) gtk_text_stream_refreshing: bool,

    // Privacy & Security
    pub(super) privacy_loading: bool,
    pub(super) privacy_busy: Option<(rmac_privacy::PortalResource, String)>,
    pub(super) privacy_reset_confirmation: Option<rmac_privacy::PortalDecision>,
    pub(super) privacy_generation: u64,
    pub(super) privacy_refresh_pending: bool,
    pub(super) privacy_stream_refreshing: bool,
    pub(super) security_coverage_loading: bool,

    // Sound
    pub(super) audio_loading: bool,
    pub(super) audio_busy: bool,
    pub(super) audio_generation: u64,
    pub(super) audio_refresh_pending: bool,
    pub(super) output_volume_generation: u64,
    pub(super) input_volume_generation: u64,
    pub(super) output_balance_generation: u64,
    pub(super) output_volume: Entity<SliderState>,
    pub(super) input_volume: Entity<SliderState>,
    pub(super) output_balance: Entity<SliderState>,
    pub(super) sound_policy: rmac_sound::Settings,
    pub(super) sound_policy_error: Option<SharedString>,
    pub(super) sound_policy_generation: u64,
    pub(super) alert_volume: Entity<SliderState>,

    // Battery and power profiles
    pub(super) power_loading: bool,
    pub(super) power_busy: bool,
    pub(super) power_generation: u64,
    pub(super) power_refresh_pending: bool,

    // Displays
    pub(super) display_loading: bool,
    pub(super) display_busy: bool,
    pub(super) display_generation: u64,
    pub(super) display_refresh_pending: bool,
    pub(super) display_confirmation: Option<DisplayConfirmation>,

    // Keyboard, mouse, and trackpad
    pub(super) input_loading: bool,
    pub(super) input_busy: bool,
    pub(super) input_generation: u64,
    pub(super) input_refresh_pending: bool,
    pub(super) input_stream_refreshing: bool,

    // Keyboard › PC Keyboard (docs/decisions/0017-mac-keyboard.md)
    pub(super) mac_keyboard: Option<rmac_keyboard::Status>,
    pub(super) mac_keyboard_busy: bool,
    pub(super) mac_keyboard_error: Option<SharedString>,
}
