[package]
name = "rmac-time-linux"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
publish = false

[dependencies]
async-channel.workspace = true
rmac-time.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
async-io.workspace = true
futures-util.workspace = true
zbus.workspace = true
