#!/usr/bin/env python3
"""Generate every rmac first-party icon from one glass recipe.

The recipe was measured from the owner's Mac Dock (macOS 26.2, Retina capture,
64 pt tiles): the visible icon is a 104 px (52 pt) squircle in a 128 px tile —
824 of a 1024 canvas — and its corner profile fits a superellipse with
n = 4.2 (inset 25, 11, 6, 1, 0 px at rows 0, 5, 10, 20, 27). Nothing is copied
from Apple's artwork; only the lighting was measured:

  body   vertical gradient, top ≈ 1.3× brighter than the bottom
  sheen  a soft white glow from the top-left
  rim    ≈ 1 px (8 of 1024) inner edge, brightest at the top-left corner
         (+65 over the body), again at the bottom-right (+50), weakest on the
         other two corners (+25)
  glyph  frosted white: opaque at the top, ≈ 80 % at the bottom, a bright
         top edge and a small soft shadow below it
  plate  no drop shadow of its own (the Dock shelf shows none)
  trash  no plate: a glass bin 94 × 102 px of the 128 px tile, 3 px below
         the plate top, 70 px wide at the base

Every plated icon is emitted in four appearances (default, dark, clear,
tinted). Outputs, all regenerated by one run:

  assets/icons/<name>[-<appearance>].svg      1024 masters for the design lab
  packaging/rmac-apps/icons/org.rmac.<App>.svg installed app icons
  crates/rmac-dock/assets/icons/<name>.svg     the Dock's embedded artwork

Installed and Dock copies declare a 128 px intrinsic size: GPUI rasterises an
SVG image at twice its intrinsic size, so 256 px covers a 64 pt tile at 2×
with room for magnification.

Usage:
    python3 scripts/build-icons.py            # rewrite every output
    python3 scripts/build-icons.py --check    # fail if any output is stale
"""

from __future__ import annotations

import math
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SIZE = 1024
PLATE = 824            # visible squircle, 52 of 64 pt in the Dock
N = 4.2                # superellipse exponent fitted to the Mac's corner
RIM = 8                # visible rim width (≈ 1 px of the 104 px plate)
GLYPH_SCALE = 1.08
LICENSE = "<!-- Original rmac artwork, MIT licensed. -->"


def squircle_path(half: float = PLATE / 2, n: float = N, steps: int = 96) -> str:
    """|x/a|^n + |y/a|^n = 1 about the canvas centre, as a closed path."""
    c = SIZE / 2
    pts = []
    for i in range(steps):
        t = 2.0 * math.pi * i / steps
        ct, st = math.cos(t), math.sin(t)
        x = math.copysign(abs(ct) ** (2.0 / n), ct) * half
        y = math.copysign(abs(st) ** (2.0 / n), st) * half
        pts.append(f"{c + x:.1f} {c + y:.1f}")
    return "M" + "L".join(pts) + "Z"


def mix(a: str, b: str, t: float) -> str:
    """Blend two #RRGGBB colours; t = 0 gives a, 1 gives b."""
    pa = [int(a[i:i + 2], 16) for i in (1, 3, 5)]
    pb = [int(b[i:i + 2], 16) for i in (1, 3, 5)]
    return "#%02X%02X%02X" % tuple(round(x + (y - x) * t) for x, y in zip(pa, pb))


def grad(gid: str, top: str, bottom: str, top_op: float = 1, bottom_op: float = 1,
         x2: float = 0, y2: float = 1) -> str:
    return (f'<linearGradient id="{gid}" x1="0" y1="0" x2="{x2}" y2="{y2}">'
            f'<stop offset="0" stop-color="{top}" stop-opacity="{top_op}"/>'
            f'<stop offset="1" stop-color="{bottom}" stop-opacity="{bottom_op}"/>'
            f'</linearGradient>')


# ---------------------------------------------------------------- glyphs
# Each icon: plate colours (top, bottom) or None for plateless artwork, the
# icon's own gradients, and the glyph. Shared ids available to every glyph:
#   url(#frost)  frosted white glyph fill      url(#edge)  bright glyph edge
#   filter url(#lift)  the glyph's soft shadow

FOLDER_BACK = ("M150 262c0-35 29-64 64-64h190c20 0 38 9 51 24l34 42h321"
               "c35 0 64 29 64 64v428c0 35-29 64-64 64H214c-35 0-64-29-64-64z")
FOLDER_FRONT = ("M150 392c0-35 29-64 64-64h596c35 0 64 29 64 64v370"
                "c0 35-29 64-64 64H214c-35 0-64-29-64-64z")
FOLDER_DEFS = (grad("fback", "#4FA8EE", "#2F7FD6")
               + grad("ffront", "#A6DBFC", "#5FAEF0"))
FOLDER = f"""
  <path d="{FOLDER_BACK}" fill="url(#fback)"/>
  <path d="{FOLDER_FRONT}" fill="url(#ffront)" filter="url(#lift)"/>
  <path d="{FOLDER_FRONT}" fill="none" stroke="url(#edge)" stroke-width="6"/>"""

TRASH_BODY = ("M152 190L226 866C230 904 258 932 298 932H726C766 932 794 904 798 866"
              "L872 190Z")
TRASH_DEFS = (
    grad("bin", "#7C808E", "#DADCE3", .92, .96)
    + grad("glass", "#FFFFFF", "#FFFFFF", .26, 0, x2=.5, y2=0)
    + grad("lip", "#FAFBFD", "#C4C7D0")
    + grad("hole", "#5F6370", "#9A9EAA")
    + grad("paper", "#FFFFFF", "#DDE1E8"))
TRASH_BIN = f"""
  <g filter="url(#lift)"><path d="{TRASH_BODY}" fill="url(#bin)"/></g>
  <path d="{TRASH_BODY}" fill="url(#glass)"/>
  <g stroke-linecap="round" stroke-width="12">
    <path d="M372 316L394 842M512 316V852M652 316L630 842" stroke="#FFFFFF" stroke-opacity=".30"/>
    <path d="M384 316L406 842M524 316V852M664 316L642 842" stroke="#6E7280" stroke-opacity=".22"/>
  </g>
  <path d="{TRASH_BODY}" fill="none" stroke="#FFFFFF" stroke-opacity=".5" stroke-width="8"/>
  <rect x="140" y="124" width="744" height="124" rx="62" fill="url(#lip)"/>
  <rect x="168" y="146" width="688" height="82" rx="41" fill="url(#hole)"/>"""
TRASH_RING = ('<rect x="146" y="130" width="732" height="112" rx="56" fill="none" '
              'stroke="#FFFFFF" stroke-width="12"/>')
TRASH_PAPERS = """
  <clipPath id="mouth"><rect x="0" y="0" width="1024" height="206"/></clipPath>
  <g clip-path="url(#mouth)" fill="url(#paper)" stroke="#B3B9C6" stroke-width="6"
     stroke-linejoin="round">
    <path d="M296 214L314 112L400 74L472 122L456 214Z"/>
    <path d="M436 214L468 64L578 42L618 116L600 214Z"/>
    <path d="M582 214L614 100L704 88L742 154L726 214Z"/>
    <path d="M400 74L420 160M578 42L540 150M704 88L672 170" fill="none"/>
  </g>"""

DOC_PAGE = ("M276 104h318l218 218v538c0 35-29 64-64 64H276c-35 0-64-29-64-64V168"
            "c0-35 29-64 64-64z")

ICONS: dict[str, tuple[tuple[str, str] | None, str, str]] = {
    "files": (("#3CC4BE", "#0C6E76"), grad("tag", "#1AA09F", "#0C6A72"), """
  <path d="M282 312h140c16 0 31 7 41 19l34 41h245c28 0 50 22 50 50v256H232V362
           c0-28 22-50 50-50z" fill="#FFFFFF" fill-opacity=".5"/>
  <path d="M282 432h460c28 0 50 22 50 50v210c0 28-22 50-50 50H282c-28 0-50-22-50-50V482
           c0-28 22-50 50-50z" fill="url(#frost)" stroke="url(#edge)" stroke-width="5"
        filter="url(#lift)"/>
  <rect x="330" y="532" width="364" height="124" rx="40" fill="url(#tag)"/>
  <circle cx="392" cy="594" r="22" fill="#EAF8F6"/>
  <path d="M446 574h168M446 616h112" stroke="#EAF8F6" stroke-width="20"
        stroke-linecap="round"/>"""),

    "apps": (("#A58CF8", "#5738CC"), "", """
  <g fill="url(#frost)" filter="url(#lift)">
    <rect x="284" y="284" width="132" height="132" rx="38"/>
    <rect x="446" y="284" width="132" height="132" rx="38"/>
    <rect x="608" y="284" width="132" height="132" rx="38"/>
    <rect x="284" y="446" width="132" height="132" rx="38"/>
    <rect x="608" y="446" width="132" height="132" rx="38"/>
    <rect x="284" y="608" width="132" height="132" rx="38"/>
    <rect x="446" y="608" width="132" height="132" rx="38"/>
    <rect x="608" y="608" width="132" height="132" rx="38"/>
  </g>
  <rect x="461" y="461" width="102" height="102" rx="26" fill="none" stroke="url(#frost)"
        stroke-width="30"/>"""),

    "notes": (("#FFD76A", "#EC9F12"), grad("band", "#F8C541", "#E9A51B") + """
  <clipPath id="page"><rect x="272" y="236" width="480" height="552" rx="56"/></clipPath>""",
              """
  <rect x="272" y="236" width="480" height="552" rx="56" fill="url(#frost)"
        filter="url(#lift)"/>
  <rect x="272" y="236" width="480" height="126" fill="url(#band)" clip-path="url(#page)"/>
  <path d="M272 362h480" stroke="#FFFFFF" stroke-opacity=".7" stroke-width="6"/>
  <path d="M336 456h352M336 536h352M336 616h232" stroke="#B98A2A" stroke-opacity=".62"
        stroke-width="24" stroke-linecap="round"/>
  <circle cx="664" cy="700" r="30" fill="#F2861C"/>
  <rect x="272" y="236" width="480" height="552" rx="56" fill="none" stroke="url(#edge)"
        stroke-width="5"/>"""),

    "text-editor": (("#5E9DFA", "#1D5AD5"), "", """
  <path d="M320 232h276l148 148v368c0 31-25 56-56 56H320c-31 0-56-25-56-56V288
           c0-31 25-56 56-56z" fill="url(#frost)" stroke="url(#edge)" stroke-width="5"
        filter="url(#lift)"/>
  <path d="M596 232v96c0 29 23 52 52 52h96z" fill="#C8DAF8"/>
  <path d="M334 448h268M334 520h268M334 592h196M334 664h232" stroke="#2E6FDB"
        stroke-opacity=".5" stroke-width="22" stroke-linecap="round"/>
  <rect x="648" y="424" width="28" height="292" rx="14" fill="#1D5AD5"/>"""),

    "terminal": (("#4A4B50", "#141416"), grad("prompt", "#FFFFFF", "#C9CCD2"), """
  <rect x="242" y="282" width="540" height="460" rx="62" fill="#0B0B0D" fill-opacity=".82"
        stroke="#FFFFFF" stroke-opacity=".14" stroke-width="5"/>
  <g filter="url(#lift)">
    <circle cx="304" cy="346" r="15" fill="#FF6159"/>
    <circle cx="350" cy="346" r="15" fill="#FFBD2E"/>
    <circle cx="396" cy="346" r="15" fill="#2ACB42"/>
    <path d="M318 462l104 82-104 82" fill="none" stroke="url(#prompt)" stroke-width="40"
          stroke-linecap="round" stroke-linejoin="round"/>
    <rect x="462" y="606" width="176" height="38" rx="19" fill="url(#prompt)"/>
  </g>"""),

    "system-settings": (("#8C99AC", "#465368"), grad("track", "#8793A6", "#A9B3C2"), """
  <rect x="262" y="282" width="500" height="460" rx="72" fill="url(#frost)"
        stroke="url(#edge)" stroke-width="5" filter="url(#lift)"/>
  <path d="M332 404h360M332 512h360M332 620h360" stroke="url(#track)" stroke-width="26"
        stroke-linecap="round"/>
  <g stroke="#FFFFFF" stroke-width="12" filter="url(#lift)">
    <circle cx="456" cy="404" r="42" fill="#3A8AF6"/>
    <circle cx="604" cy="512" r="42" fill="#30BE68"/>
    <circle cx="398" cy="620" r="42" fill="#F2892C"/>
  </g>"""),

    "system-monitor": (("#46CB88", "#137043"), grad("pulse", "#D6FFE8", "#5CE59C"), """
  <rect x="252" y="282" width="520" height="460" rx="66" fill="#0C3522" fill-opacity=".86"
        stroke="#FFFFFF" stroke-opacity=".2" stroke-width="5"/>
  <path d="M312 352h96M616 352h96" stroke="#7BE8AF" stroke-opacity=".6" stroke-width="20"
        stroke-linecap="round"/>
  <path d="M312 440h400M312 540h400M312 640h400" stroke="#7BE8AF" stroke-opacity=".12"
        stroke-width="6"/>
  <path d="M312 548h112l44-104 64 212 58-164 42 56h80" fill="none" stroke="url(#pulse)"
        stroke-width="36" stroke-linecap="round" stroke-linejoin="round"
        filter="url(#lift)"/>"""),

    "calculator": (("#595A60", "#1D1E21"), grad("op", "#FFB54A", "#FF8500"), """
  <rect x="300" y="236" width="424" height="552" rx="66" fill="#111114" fill-opacity=".9"
        stroke="#FFFFFF" stroke-opacity=".12" stroke-width="5" filter="url(#lift)"/>
  <rect x="340" y="276" width="344" height="112" rx="30" fill="#2A2B30"/>
  <rect x="560" y="320" width="92" height="26" rx="13" fill="#F4F4F6"/>
  <g fill="#BABCC2">
    <circle cx="392" cy="462" r="32"/><circle cx="472" cy="462" r="32"/>
    <circle cx="552" cy="462" r="32"/>
  </g>
  <g fill="#4C4E55">
    <circle cx="392" cy="542" r="32"/><circle cx="472" cy="542" r="32"/>
    <circle cx="552" cy="542" r="32"/><circle cx="392" cy="622" r="32"/>
    <circle cx="472" cy="622" r="32"/><circle cx="552" cy="622" r="32"/>
    <circle cx="392" cy="702" r="32"/><circle cx="472" cy="702" r="32"/>
    <circle cx="552" cy="702" r="32"/>
  </g>
  <g fill="url(#op)">
    <circle cx="632" cy="462" r="32"/><circle cx="632" cy="542" r="32"/>
    <circle cx="632" cy="622" r="32"/><circle cx="632" cy="702" r="32"/>
  </g>"""),

    "preview": (("#6BA8F8", "#2A60D0"), grad("sky", "#A6D5FF", "#5C9DF0")
                + grad("hill", "#58B26E", "#2F7F48") + """
  <clipPath id="photo"><rect x="336" y="284" width="292" height="190" rx="20"/></clipPath>""",
                """
  <rect x="292" y="240" width="380" height="480" rx="44" fill="url(#frost)"
        stroke="url(#edge)" stroke-width="5" filter="url(#lift)"/>
  <g clip-path="url(#photo)">
    <rect x="336" y="284" width="292" height="190" fill="url(#sky)"/>
    <circle cx="578" cy="330" r="24" fill="#FFE27A"/>
    <path d="M336 474V418l76-72 62 58 48-38 106 84v24z" fill="url(#hill)"/>
  </g>
  <path d="M336 540h292M336 596h292M336 652h176" stroke="#9DB0C8" stroke-width="22"
        stroke-linecap="round"/>
  <g filter="url(#lift)">
    <circle cx="640" cy="628" r="96" fill="#FFFFFF" fill-opacity=".28" stroke="#16284A"
            stroke-width="40"/>
    <path d="M712 700l70 70" stroke="#16284A" stroke-width="50" stroke-linecap="round"/>
  </g>"""),

    "application": (("#A3ACBB", "#5A6679"), grad("pane", "#5A96F7", "#2C60D2"), """
  <rect x="252" y="292" width="520" height="440" rx="60" fill="url(#frost)"
        stroke="url(#edge)" stroke-width="5" filter="url(#lift)"/>
  <path d="M252 388h520" stroke="#AEB7C6" stroke-opacity=".6" stroke-width="5"/>
  <g fill="#8A95A8">
    <circle cx="314" cy="340" r="14"/><circle cx="356" cy="340" r="14"/>
    <circle cx="398" cy="340" r="14"/>
  </g>
  <rect x="300" y="432" width="170" height="252" rx="26" fill="#7F8BA0" fill-opacity=".45"/>
  <rect x="500" y="432" width="224" height="104" rx="26" fill="url(#pane)"/>
  <rect x="500" y="564" width="224" height="120" rx="26" fill="#7F8BA0" fill-opacity=".32"/>"""),

    "more": (("#8C929B", "#4E545D"), "", """
  <g fill="url(#frost)" filter="url(#lift)">
    <circle cx="372" cy="512" r="44"/><circle cx="512" cy="512" r="44"/>
    <circle cx="652" cy="512" r="44"/>
  </g>"""),

    "folder": (None, FOLDER_DEFS, FOLDER),

    "downloads": (None, FOLDER_DEFS, FOLDER + """
  <path d="M512 456v212M424 584l88 88 88-88" fill="none" stroke="#2A7ED4"
        stroke-opacity=".8" stroke-width="44" stroke-linecap="round"
        stroke-linejoin="round"/>"""),

    "document": (None, grad("paper", "#FFFFFF", "#EDF0F5"), f"""
  <path d="{DOC_PAGE}" fill="url(#paper)" filter="url(#lift)"/>
  <path d="{DOC_PAGE}" fill="none" stroke="#C6CCD6" stroke-width="4"/>
  <path d="M594 104v154c0 35 29 64 64 64h154z" fill="#DCE1EA"/>"""),

    "trash": (None, TRASH_DEFS, TRASH_BIN + TRASH_RING),

    "trash-full": (None, TRASH_DEFS, TRASH_BIN + TRASH_PAPERS + TRASH_RING),
}

APPEARANCES = ("default", "dark", "clear", "tinted")

# Installed application identities -> icon name.
PACKAGED = {
    "org.rmac.Files": "files",
    "org.rmac.AppDrawer": "apps",
    "org.rmac.Notes": "notes",
    "org.rmac.TextEditor": "text-editor",
    "org.rmac.Terminal": "terminal",
    "org.rmac.SystemSettings": "system-settings",
    "org.rmac.SystemMonitor": "system-monitor",
    "org.rmac.Calculator": "calculator",
    "org.rmac.Preview": "preview",
}

# The Dock's embedded artwork -> icon name (Application is the fallback for
# every application that ships no icon of its own).
DOCK = {
    "application": "application",
    "files": "files",
    "downloads": "downloads",
    "trash-empty": "trash",
    "trash-full": "trash-full",
    "more": "more",
}


def build(name: str, appearance: str = "default", px: int = SIZE) -> str:
    plate_colours, icon_defs, glyph = ICONS[name]
    shadow = "#000000"
    parts = []
    defs = [icon_defs]

    if plate_colours is not None:
        top, bottom = plate_colours
        if appearance == "dark":
            top, bottom = mix(top, "#000000", .45), mix(bottom, "#000000", .55)
        elif appearance == "clear":
            top, bottom = "#FFFFFF", "#DCDCE2"
        shadow = mix(bottom, "#000000", .5)
        plate = squircle_path()
        defs += [
            f'<clipPath id="sq"><path d="{plate}"/></clipPath>',
            grad("body", top, bottom, *((.30, .22) if appearance == "clear" else (1, 1))),
            '<radialGradient id="sheen" cx=".22" cy=".06" r=".9">'
            '<stop offset="0" stop-color="#FFFFFF" stop-opacity=".22"/>'
            '<stop offset=".6" stop-color="#FFFFFF" stop-opacity="0"/></radialGradient>',
            '<linearGradient id="rim" x1="0" y1="0" x2="1" y2="1">'
            '<stop offset="0" stop-color="#FFFFFF" stop-opacity=".78"/>'
            '<stop offset=".32" stop-color="#FFFFFF" stop-opacity=".28"/>'
            '<stop offset=".62" stop-color="#FFFFFF" stop-opacity=".2"/>'
            '<stop offset="1" stop-color="#FFFFFF" stop-opacity=".6"/></linearGradient>',
        ]
        parts.append(f"""<g clip-path="url(#sq)">
  <rect x="0" y="0" width="{SIZE}" height="{SIZE}" fill="url(#body)"/>
  <rect x="0" y="0" width="{SIZE}" height="{SIZE}" fill="url(#sheen)"/>
  <path d="{plate}" fill="none" stroke="url(#rim)" stroke-width="{2 * RIM}"/>
</g>""")

    defs += [
        grad("frost", "#FFFFFF", mix("#FFFFFF", plate_colours[0] if plate_colours else
                                     "#FFFFFF", .12), 1, .82),
        grad("edge", "#FFFFFF", "#FFFFFF", .95, .3),
        '<filter id="lift" x="-20%" y="-20%" width="140%" height="150%">'
        f'<feDropShadow dx="0" dy="10" stdDeviation="12" flood-color="{shadow}" '
        'flood-opacity=".3"/></filter>',
    ]
    if appearance == "tinted":
        defs.append('<filter id="mono"><feColorMatrix type="saturate" values="0"/></filter>')
    if appearance == "dark" and plate_colours is None:
        defs.append('<filter id="dim"><feColorMatrix type="matrix" values=".78 0 0 0 0 '
                    '0 .78 0 0 0 0 0 .8 0 0 0 0 0 1 0"/></filter>')

    wrap = {"clear": '<g opacity=".9">'}.get(
        appearance, '<g filter="url(#dim)">' if appearance == "dark"
        and plate_colours is None else "<g>")
    if plate_colours is not None:
        # Glyphs are drawn on a 1024 grid and enlarged about the centre so
        # they fill the plate as the Mac's do (≈ 70 % of its width).
        glyph = f'<g transform="translate(512 512) scale({GLYPH_SCALE}) translate(-512 -512)">{glyph}</g>'
    parts.append(f"{wrap}{glyph}\n</g>")

    body = "\n".join(parts)
    if appearance == "tinted":
        # Monochrome: the whole icon, plate included, loses its colour.
        body = f'<g filter="url(#mono)">\n{body}\n</g>'
    size_attr = f' width="{px}" height="{px}"'
    return (f'<?xml version="1.0" encoding="UTF-8"?>\n{LICENSE}\n'
            f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {SIZE} {SIZE}"{size_attr}>\n'
            f'<defs>{"".join(defs)}</defs>\n{body}\n</svg>\n')


def outputs() -> dict[Path, str]:
    files: dict[Path, str] = {}
    for name in ICONS:
        for appearance in APPEARANCES:
            suffix = "" if appearance == "default" else f"-{appearance}"
            files[ROOT / "assets/icons" / f"{name}{suffix}.svg"] = build(name, appearance)
    for identity, name in PACKAGED.items():
        files[ROOT / "packaging/rmac-apps/icons" / f"{identity}.svg"] = build(name, px=128)
    for file, name in DOCK.items():
        files[ROOT / "crates/rmac-dock/assets/icons" / f"{file}.svg"] = build(name, px=128)
    return files


def main(argv: list[str]) -> int:
    files = outputs()
    if "--check" in argv:
        stale = [p for p, text in files.items()
                 if not p.is_file() or p.read_text() != text]
        for path in stale:
            print(f"stale: {path.relative_to(ROOT)}")
        return 1 if stale else 0
    for path, text in files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)
    print(f"wrote {len(files)} icons; preview them in design-lab/icons.html")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
