[package]
name = "rmac-shell-status"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
publish = false

[dependencies]
rmac-audio.workspace = true
rmac-bluetooth.workspace = true
rmac-compositor.workspace = true
rmac-network.workspace = true
rmac-power.workspace = true
rmac-shell-settings.workspace = true
