//! Shortcut validation and niri fallback serialization.

use super::*;

pub fn validate_specs(shortcuts: &[ShortcutSpec]) -> Result<(), Error> {
    let mut ids = std::collections::BTreeSet::new();
    let mut portal_triggers = std::collections::BTreeSet::new();
    let mut niri_triggers = std::collections::BTreeSet::new();
    for shortcut in shortcuts {
        if shortcut.id.0.is_empty()
            || !shortcut.id.0.bytes().all(|byte| {
                byte.is_ascii_lowercase() || byte.is_ascii_digit() || b".-".contains(&byte)
            })
        {
            return Err(Error::new(
                Operation::Validate,
                format!("invalid shortcut id {}", shortcut.id.0),
            ));
        }
        if !ids.insert(&shortcut.id.0) {
            return Err(Error::new(
                Operation::Validate,
                "shortcut IDs must be unique",
            ));
        }
        validate_text(&shortcut.description, "shortcut description")?;
        validate_portal_trigger(&shortcut.preferred_trigger)?;
        validate_niri_trigger(&shortcut.niri_trigger)?;
        if !portal_triggers.insert(&shortcut.preferred_trigger)
            || !niri_triggers.insert(&shortcut.niri_trigger)
        {
            return Err(Error::new(
                Operation::Validate,
                "shortcut triggers must be unique",
            ));
        }
    }
    Ok(())
}

pub(super) fn validate_text(value: &str, label: &str) -> Result<(), Error> {
    if value.trim().is_empty() || value.len() > 256 || value.chars().any(char::is_control) {
        Err(Error::new(
            Operation::Validate,
            format!("{label} must be non-empty, bounded, and contain no control characters"),
        ))
    } else {
        Ok(())
    }
}

pub(super) fn validate_portal_trigger(trigger: &str) -> Result<(), Error> {
    let mut parts = trigger.split('+').peekable();
    let mut saw_key = false;
    while let Some(part) = parts.next() {
        if part.is_empty()
            || !part
                .bytes()
                .all(|byte| byte.is_ascii_alphanumeric() || byte == b'_')
        {
            return Err(Error::new(
                Operation::Validate,
                "invalid portal shortcut trigger",
            ));
        }
        if parts.peek().is_none() {
            saw_key = true;
        } else if !matches!(part, "CTRL" | "ALT" | "SHIFT" | "NUM" | "LOGO") {
            return Err(Error::new(
                Operation::Validate,
                format!("unsupported portal modifier {part}"),
            ));
        }
    }
    if saw_key {
        Ok(())
    } else {
        Err(Error::new(Operation::Validate, "portal trigger has no key"))
    }
}

pub(super) fn validate_niri_trigger(trigger: &str) -> Result<(), Error> {
    if trigger.is_empty()
        || trigger.len() > 128
        || !trigger
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'+' | b'_'))
    {
        Err(Error::new(
            Operation::Validate,
            "invalid niri shortcut trigger",
        ))
    } else {
        Ok(())
    }
}

pub fn render_niri_fallback(
    shortcuts: &[ShortcutSpec],
    dispatcher: &Path,
) -> Result<String, Error> {
    validate_specs(shortcuts)?;
    if !dispatcher.is_absolute() {
        return Err(Error::new(
            Operation::WriteFallback,
            "dispatcher path must be absolute",
        ));
    }
    let dispatcher = dispatcher
        .to_str()
        .ok_or_else(|| Error::new(Operation::WriteFallback, "dispatcher path must be UTF-8"))?;
    validate_text(dispatcher, "dispatcher path")?;
    let mut output = String::from(
        "// Generated by rmac. Include this file only when the GlobalShortcuts portal is unavailable.\n\n",
    );
    output.push_str("binds {\n");
    for shortcut in shortcuts {
        let allow_when_locked = if shortcut.id.0 == "lock" {
            " allow-when-locked=true"
        } else {
            ""
        };
        output.push_str(&format!(
            "    {} repeat=false{} hotkey-overlay-title=\"{}\" {{ spawn \"{}\" \"{}\"; }}\n",
            shortcut.niri_trigger,
            allow_when_locked,
            escape_kdl(&shortcut.description),
            escape_kdl(dispatcher),
            shortcut.id.0,
        ));
    }
    output.push_str("}\n");
    Ok(output)
}

pub(super) fn escape_kdl(value: &str) -> String {
    value.replace('\\', "\\\\").replace('"', "\\\"")
}

pub fn write_niri_fallback(path: &Path, dispatcher: &Path) -> Result<(), Error> {
    let contents = render_niri_fallback(&default_shortcuts(), dispatcher)?;
    let parent = path
        .parent()
        .ok_or_else(|| Error::new(Operation::WriteFallback, "fallback path has no parent"))?;
    std::fs::create_dir_all(parent)
        .map_err(|error| Error::new(Operation::WriteFallback, error.to_string()))?;
    atomic_write(path, contents.as_bytes())
        .map_err(|error| Error::new(Operation::WriteFallback, error.to_string()))
}
