//! Focused global-shortcut contracts.

use super::*;

#[test]
fn defaults_use_unique_standard_and_niri_triggers() {
    let shortcuts = default_shortcuts();
    validate_specs(&shortcuts).unwrap();
    assert_eq!(shortcuts.len(), 2);
    assert!(shortcuts.iter().all(|shortcut| {
        shortcut.preferred_trigger.starts_with("LOGO+") && shortcut.niri_trigger.starts_with("Mod+")
    }));
}

#[test]
fn fallback_is_explicit_shell_free_and_uses_one_dispatcher() {
    let output = render_niri_fallback(
        &default_shortcuts(),
        Path::new("/home/test/.local/libexec/rmac/rmac-shortcut-dispatch"),
    )
    .unwrap();
    assert!(output.starts_with("// Generated by Lulo OS"));
    assert_eq!(output.matches("{ spawn ").count(), 2);
    assert!(!output.contains("spawn-sh"));
    assert!(!output.contains("sh -c"));
    assert!(output.contains("repeat=false"));
    assert_eq!(output.matches("allow-when-locked=true").count(), 1);
    assert!(output.contains("Mod+Ctrl+Q repeat=false allow-when-locked=true"));
}

#[test]
fn packaged_fallback_matches_the_typed_shortcut_domain() {
    let output = render_niri_fallback(
        &default_shortcuts(),
        Path::new("/usr/libexec/rmac/rmac-shortcut-dispatch"),
    )
    .unwrap();
    assert_eq!(
        output,
        include_str!("../../../packaging/rmac-session/shortcuts-fallback.kdl")
    );
}

#[test]
fn generated_niri_mode_never_combines_portal_and_fallback_bindings() {
    let root = std::env::temp_dir().join(format!(
        "rmac-shortcut-mode-{}-{}",
        std::process::id(),
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .subsec_nanos()
    ));
    let path = root.join("rmac/niri/shortcuts-generated.kdl");
    let dispatcher = Path::new("/usr/libexec/rmac/rmac-shortcut-dispatch");
    write_niri_binding_mode(
        &path,
        dispatcher,
        &BackendStatus::FallbackRequired {
            reason: "test".into(),
        },
    )
    .unwrap();
    let fallback = std::fs::read_to_string(&path).unwrap();
    assert!(fallback.contains("Mod+Space"));
    assert_eq!(fallback.matches("{ spawn ").count(), 2);

    write_niri_binding_mode(
        &path,
        dispatcher,
        &BackendStatus::Portal {
            version: 2,
            can_configure: true,
        },
    )
    .unwrap();
    let portal = std::fs::read_to_string(&path).unwrap();
    assert!(portal.contains("GlobalShortcuts portal owns"));
    assert!(!portal.contains("binds"));
    std::fs::remove_dir_all(root).unwrap();
}

#[test]
fn rejects_duplicate_or_malformed_shortcuts_and_relative_dispatchers() {
    let mut shortcuts = default_shortcuts();
    shortcuts[1].id = shortcuts[0].id.clone();
    assert!(validate_specs(&shortcuts).is_err());
    assert!(render_niri_fallback(&default_shortcuts(), Path::new("relative")).is_err());
}

#[test]
fn duration_conversion_is_bounded() {
    assert_eq!(duration_ms(std::time::Duration::from_millis(42)), 42);
}

#[test]
fn backend_status_snapshot_is_typed_and_rejects_malformed_data() {
    let path = std::env::temp_dir().join(format!(
        "rmac-shortcuts-status-{}-{}.json",
        std::process::id(),
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_nanos()
    ));
    std::fs::write(
        &path,
        br#"{"kind":"portal","version":2,"can_configure":true}"#,
    )
    .unwrap();
    assert_eq!(
        backend_status_at(&path).unwrap(),
        BackendStatus::Portal {
            version: 2,
            can_configure: true,
        }
    );
    std::fs::write(&path, b"not json").unwrap();
    assert_eq!(
        backend_status_at(&path).unwrap_err().operation,
        Operation::ParseStatus
    );
    std::fs::remove_file(path).unwrap();
}

#[test]
fn dispatcher_rejects_unknown_ids_before_touching_the_runtime_socket() {
    let error = dispatch(&ShortcutId("not-an-rmac-action".into())).unwrap_err();
    assert_eq!(error.operation, Operation::Dispatch);
    assert!(error.detail.contains("unknown shortcut"));
}

#[test]
fn dispatcher_endpoints_are_action_scoped() {
    let runtime = Path::new("/tmp/rmac-shortcuts-test");
    let launcher = shortcut_socket_path_in(runtime, &ShortcutId("launcher".into())).unwrap();
    let drawer = shortcut_socket_path_in(runtime, &ShortcutId("app-drawer".into())).unwrap();
    assert_ne!(launcher, drawer);
    assert!(launcher.ends_with("shortcut-launcher.sock"));
    assert!(drawer.ends_with("shortcut-app-drawer.sock"));
    assert!(shortcut_socket_path_in(runtime, &ShortcutId("unknown".into())).is_err());
}

#[test]
fn the_power_button_and_its_dialog_have_their_own_endpoints() {
    let runtime = Path::new("/tmp/rmac-shortcuts-test");
    let press = ShortcutId(power_key::POWER_KEY_SHORTCUT.into());
    let dialog = ShortcutId(power_key::SHUTDOWN_DIALOG_SHORTCUT.into());
    assert!(shortcut_socket_path_in(runtime, &press)
        .unwrap()
        .ends_with("shortcut-power-key.sock"));
    assert!(shortcut_socket_path_in(runtime, &dialog)
        .unwrap()
        .ends_with("shortcut-shutdown-dialog.sock"));
    // Neither is a user shortcut: niri binds the key itself in shell.kdl,
    // so neither is offered to the GlobalShortcuts portal or the fallback.
    assert!(!default_shortcuts()
        .iter()
        .any(|spec| spec.id == press || spec.id == dialog));
}

#[test]
fn ctrl_f2_moves_menu_bar_focus_through_its_own_endpoint() {
    let runtime = Path::new("/tmp/rmac-shortcuts-test");
    let focus = ShortcutId("menu-bar-focus".into());
    assert!(known_action(&focus));
    assert!(shortcut_socket_path_in(runtime, &focus)
        .unwrap()
        .ends_with("shortcut-menu-bar-focus.sock"));
    // Not a user shortcut: niri binds Ctrl+F2 itself in shell.kdl, the same
    // way it binds the power key, so this isn't offered to the
    // GlobalShortcuts portal or the fallback either.
    assert!(!default_shortcuts().iter().any(|spec| spec.id == focus));
}

#[test]
fn software_update_restarts_through_its_own_endpoint() {
    let runtime = Path::new("/tmp/rmac-shortcuts-test");
    let restart = ShortcutId(power_key::RESTART_TO_UPDATE_SHORTCUT.into());
    assert!(known_action(&restart));
    assert!(shortcut_socket_path_in(runtime, &restart)
        .unwrap()
        .ends_with("shortcut-restart-to-update.sock"));
    // Only System Settings sends it; no key or portal shortcut does.
    assert!(!default_shortcuts().iter().any(|spec| spec.id == restart));
}

#[cfg(unix)]
#[test]
fn configuration_request_is_session_scoped_acknowledged_and_cleans_up() {
    let root = PathBuf::from("/tmp").join(format!(
        "rmac-shortcut-control-{}-{}",
        std::process::id(),
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .subsec_nanos()
    ));
    let directory = root.join("rmac");
    std::fs::create_dir_all(&directory).unwrap();
    {
        use std::os::unix::fs::PermissionsExt as _;
        std::fs::set_permissions(&directory, std::fs::Permissions::from_mode(0o700)).unwrap();
    }
    let server_path = control_socket_path_in(&root);
    let server = std::os::unix::net::UnixDatagram::bind(&server_path).unwrap();
    server
        .set_read_timeout(Some(std::time::Duration::from_secs(2)))
        .unwrap();
    let broker = std::thread::spawn(move || {
        let mut buffer = [0u8; 256];
        let (length, peer) = server.recv_from(&mut buffer).unwrap();
        let request: ConfigureRequest = serde_json::from_slice(&buffer[..length]).unwrap();
        assert_eq!(request.version, CONTROL_PROTOCOL_VERSION);
        assert_eq!(request.request_id, 41);
        {
            use std::os::unix::fs::PermissionsExt as _;
            let reply_path = peer.as_pathname().unwrap();
            assert_eq!(
                std::fs::symlink_metadata(reply_path)
                    .unwrap()
                    .permissions()
                    .mode()
                    & 0o077,
                0
            );
        }
        let response = ConfigureResponse {
            version: CONTROL_PROTOCOL_VERSION,
            request_id: request.request_id,
            outcome: ConfigureOutcome::Requested,
        };
        server
            .send_to(
                &serde_json::to_vec(&response).unwrap(),
                peer.as_pathname().unwrap(),
            )
            .unwrap();
    });

    request_shortcut_configuration_at(&root, 41).unwrap();
    broker.join().unwrap();
    let remaining: Vec<_> = std::fs::read_dir(&directory)
        .unwrap()
        .map(|entry| entry.unwrap().file_name())
        .collect();
    assert_eq!(
        remaining,
        [std::ffi::OsString::from("shortcut-broker-control.sock")]
    );
    std::fs::remove_dir_all(root).unwrap();
}

#[test]
fn configuration_requests_are_coalesced_only_inside_the_bounded_cooldown() {
    let now = std::time::Instant::now();
    assert!(!configuration_request_is_coalesced(None, now));
    assert!(configuration_request_is_coalesced(
        Some(now - std::time::Duration::from_secs(1)),
        now
    ));
    assert!(!configuration_request_is_coalesced(
        Some(now - CONFIGURATION_REQUEST_COOLDOWN),
        now
    ));
}

#[test]
fn action_listener_accepts_only_its_typed_dispatch_and_cleans_up() {
    let root = PathBuf::from("/tmp").join(format!(
        "rmac-shortcut-{}-{}",
        std::process::id(),
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .subsec_nanos()
    ));
    let path = root.join("shortcut-launcher.sock");
    let id = ShortcutId("launcher".into());
    let (sender, receiver) = async_channel::bounded(2);
    let (ready_sender, ready_receiver) = async_channel::bounded(1);
    async_io::block_on(async {
        let listener = watch_dispatches_at(path.clone(), id.clone(), sender, Some(ready_sender));
        let client = async {
            ready_receiver.recv().await.unwrap();
            let socket = std::os::unix::net::UnixDatagram::unbound().unwrap();
            socket.send_to(br#""not-a-shortcut""#, &path).unwrap();
            socket
                .send_to(&serde_json::to_vec(&id).unwrap(), &path)
                .unwrap();
            assert_eq!(
                receiver.recv().await.unwrap(),
                Event::Activated {
                    id: id.clone(),
                    timestamp_ms: 1,
                }
            );
            receiver.close();
            socket
                .send_to(&serde_json::to_vec(&id).unwrap(), &path)
                .unwrap();
        };
        let (result, ()) = futures_util::join!(listener, client);
        result.unwrap();
    });
    assert!(!path.exists());
    std::fs::remove_dir_all(root).unwrap();
}

#[test]
fn portal_retries_back_off_to_five_minutes() {
    use std::time::Duration;
    assert_eq!(portal_retry_delay(0), Duration::from_secs(2));
    assert_eq!(portal_retry_delay(1), Duration::from_secs(2));
    assert_eq!(portal_retry_delay(2), Duration::from_secs(4));
    assert_eq!(portal_retry_delay(3), Duration::from_secs(8));
    assert_eq!(portal_retry_delay(8), Duration::from_secs(256));
    assert_eq!(portal_retry_delay(9), Duration::from_secs(300));
    assert_eq!(portal_retry_delay(u32::MAX), Duration::from_secs(300));
}
