[package]
name = "rmac-shell-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
publish = false

[dependencies]
async-channel.workspace = true
async-io.workspace = true
blocking.workspace = true
futures-util.workspace = true
rmac-audio.workspace = true
rmac-bluetooth.workspace = true
rmac-compositor.workspace = true
rmac-compositor-niri.workspace = true
rmac-network.workspace = true
rmac-power.workspace = true
rmac-shell-settings.workspace = true
rmac-shell-status.workspace = true
rmac-shell-status-linux.workspace = true
