[package]
name = "rmac-network"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
async-channel.workspace = true
url.workspace = true
zeroize.workspace = true

[target.'cfg(not(target_os = "macos"))'.dependencies]
async-io.workspace = true
futures-util.workspace = true
libloading.workspace = true
zbus.workspace = true

[dev-dependencies]
zbus.workspace = true
