[package]
name = "rmac-app-drawer"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[[bin]]
name = "rmac-app-drawer"
path = "src/main.rs"

[dependencies]
gpui.workspace = true
gpui-component.workspace = true
rmac-apps.workspace = true
rmac-ui.workspace = true
