//! Settings entity construction and explicit initial state.

use super::*;

impl Settings {
    pub(in crate::controller) fn new(window: &mut Window, cx: &mut Context<Self>) -> Self {
        let search = cx.new(|cx| {
            InputState::new(window, cx)
                .placeholder(rmac_system_settings::accessibility::SEARCH_NAME)
        });
        cx.observe(&search, |this: &mut Settings, _, cx| {
            this.search_selection = 0;
            cx.notify();
        })
        .detach();

        let (catalog_events, catalog_event_rx) = async_channel::bounded(1);
        let app_catalog_watcher = rmac_apps::watch_catalog(move || {
            let _ = catalog_events.try_send(());
        })
        .ok();

        // System audio sliders write through the platform audio service.
        let output_volume = Self::audio_slider(cx, 0.0, rmac_audio::DeviceKind::Output);
        let input_volume = Self::audio_slider(cx, 0.0, rmac_audio::DeviceKind::Input);
        let output_balance = Self::audio_balance_slider(cx, 0.0);
        // Replaced once the initial backlight read lands (start_snapshot_loads).
        let brightness_slider = Self::brightness_slider(cx, 0.0);
        // Replaced once the first shell-settings snapshot lands, and again
        // whenever it changes from elsewhere (e.g. the Dock's own
        // separator drag, DOCK-03).
        let dock_size_slider =
            Self::dock_size_slider(cx, rmac_shell_settings::DEFAULT_DOCK_TILE_SIZE);
        let dock_magnification_slider = Self::dock_magnification_slider(cx, 0.0);
        // Replaced once the initial input snapshot lands (finish_input_update).
        let keyboard_repeat_rate_slider = Self::keyboard_repeat_rate_slider(cx, 0.0);
        let keyboard_repeat_delay_slider = Self::keyboard_repeat_delay_slider(cx, 0.0);
        let (sound_policy, sound_policy_error) = match rmac_sound::load_settings() {
            Ok(settings) => (settings, None),
            Err(error) => (
                rmac_sound::Settings::default(),
                Some(format!("Could not load interface sound settings: {error}").into()),
            ),
        };
        let alert_volume =
            Self::sound_policy_volume_slider(cx, f32::from(sound_policy.alert_volume));

        Self::start_watchers(cx, catalog_event_rx);

        let (sections, selected, nav, navigation_persistence) = Self::initial_navigation(cx);

        Self {
            system_data_loading: true,
            system_data_busy: false,
            system_data_error: None,
            system_data_stream_error: None,
            system_data_generation: 0,
            system_data_refresh_pending: false,
            system_data_stream_refreshing: false,
            hostname_editor: None,
            diagnostics_copied: false,
            account: std::env::var("USER")
                .unwrap_or_else(|_| "User".into())
                .into(),
            sysinfo: rmac_system_info::Snapshot::default(),
            screen_reader: ScreenReaderCapability::default(),
            screen_reader_loading: true,
            updates_loading: true,
            updates_busy: false,
            updates_error: None,
            updates_stream_error: None,
            updates_generation: 0,
            updates_refresh_pending: false,
            updates_stream_refreshing: false,
            updates_preparing: false,
            updates_installing: false,
            updates_cancellation: None,
            updates_plan: None,
            updates_progress: None,
            updates_result: None,
            updates: None,
            time_loading: true,
            time_busy: false,
            time_error: None,
            time_stream_error: None,
            time_generation: 0,
            time_refresh_pending: false,
            time_stream_refreshing: false,
            clock_editor: None,
            clock_confirmation: None,
            clock_setting: false,
            time: None,
            timezone_editor: None,
            locale_loading: true,
            locale_busy: false,
            locale_error: None,
            locale_stream_error: None,
            locale_generation: 0,
            locale_refresh_pending: false,
            locale_stream_refreshing: false,
            locale: None,
            locale_editor: None,
            region_editor: None,
            locale_revert: None,
            x11_layout_editor: None,
            x11_variant_editor: None,
            x11_options_editor: None,
            x11_keyboard_revert: None,
            login_items_loading: true,
            login_item_busy: None,
            login_items_error: None,
            login_items_stream_error: None,
            login_items_generation: 0,
            login_items_refresh_pending: false,
            login_items_stream_refreshing: false,
            login_items: None,
            login_item_add: None,
            login_item_remove: None,
            sharing_loading: true,
            sharing_busy: false,
            sharing_error: None,
            sharing_stream_error: None,
            sharing: None,
            sharing_confirmation: None,
            file_sharing_confirmation: None,
            power: rmac_power::Snapshot::default(),
            display: rmac_display::Snapshot::default(),
            brightness: None,
            brightness_slider,
            brightness_generation: 0,
            brightness_error: None,
            dock_size_slider,
            dock_magnification_slider,
            network: rmac_network::NetworkSnapshot::default(),
            storage: Vec::new(),
            storage_busy: false,
            storage_error: None,
            storage_stream_error: None,
            storage_generation: 0,
            storage_refresh_pending: false,
            storage_stream_refreshing: false,
            storage_action_busy: None,
            audio: rmac_audio::Snapshot::default(),
            input: rmac_input::Snapshot::default(),
            keyboard_repeat_rate_slider,
            keyboard_repeat_delay_slider,
            gtk_text: None,
            screen_reader_toggle: None,
            privacy: None,
            security_coverage: None,
            sections,
            selected,
            navigation_persistence,
            nav,
            forward: Vec::new(),
            sidebar_focused: false,
            search,
            search_selection: 0,
            compact_sidebar_open: false,
            trackpad_tab: 0,
            storage_categories: None,
            storage_categories_busy: false,
            keyboard_shortcuts_open: false,
            keyboard_shortcuts_category: 0,
            focus: cx.focus_handle(),
            content_focus: cx.focus_handle(),
            native_window_title: "Settings".into(),
            focused_once: false,
            wifi_error: None,
            wifi_stream_error: None,
            bluetooth_error: None,
            bluetooth_stream_error: None,
            network_error: None,
            network_stream_error: None,
            vpn_error: None,
            vpn_stream_error: None,
            audio_error: None,
            audio_stream_error: None,
            power_error: None,
            power_stream_error: None,
            display_error: None,
            input_error: None,
            input_stream_error: None,
            theme_error: None,
            theme_store_stream_error: None,
            theme_portal_stream_error: None,
            shell_settings_error: None,
            shell_settings_stream_error: None,
            gtk_text_error: None,
            gtk_text_stream_error: None,
            screen_reader_toggle_error: None,
            screen_reader_toggle_stream_error: None,
            privacy_error: None,
            privacy_stream_error: None,
            notification_error: None,
            notification_stream_error: None,

            notifications_loading: true,
            notification_busy: None,
            notification_apps: Vec::new(),
            notification_origins: std::collections::BTreeMap::new(),
            app_catalog: Vec::new(),
            _app_catalog_watcher: app_catalog_watcher,

            focus_policy_loading: true,
            focus_policy_busy: false,
            focus_policy_error: None,
            focus_policy_stream_error: None,
            focus_policy_config: None,
            focus_policy_state: None,

            lock_policy_loading: true,
            lock_policy_busy: false,
            lock_policy_error: None,
            lock_policy_stream_error: None,
            lock_policy: None,
            lock_request_busy: false,
            lock_request_error: None,

            shell_settings_loading: true,
            shell_settings_busy: false,
            shell_settings: None,
            dock_compositor: rmac_compositor::State::default(),
            wallpaper_target: WallpaperTarget::Default,
            wallpaper_error: None,
            wallpaper_preview: None,
            wallpaper_preview_loading: true,
            wallpaper_preview_error: None,
            wallpaper_preview_watch_error: None,
            wallpaper_preview_generation: 0,
            _wallpaper_preview_watcher: None,
            spotlight_revert: None,
            spotlight_error: None,
            recent_history_confirmation: false,
            recent_history_busy: false,
            recent_history_notice: None,
            shortcut_status_loading: true,
            shortcut_status: None,
            shortcut_status_error: None,
            shortcut_configuration_busy: false,
            shortcut_configuration_error: None,

            network_loading: true,
            network_busy: false,
            network_generation: 0,
            network_editor: None,

            vpn: rmac_network::VpnSnapshot::default(),
            vpn_loading: true,
            vpn_refreshing: false,
            vpn_busy: None,
            vpn_cancellation: None,
            vpn_generation: 0,
            vpn_import_capabilities: rmac_network::VpnImportCapabilities::default(),
            vpn_import_loading: true,
            vpn_import_busy: false,
            vpn_import_preview: None,
            vpn_editor_loading: None,
            vpn_editor_busy: false,
            vpn_editor: None,
            vpn_secret_preparing: false,
            vpn_secret_busy: false,
            vpn_secret_preview: None,
            vpn_delete_preparing: None,
            vpn_delete_busy: false,
            vpn_delete_preview: None,

            wifi_available: false,
            wifi_loading: true,
            wifi_busy: false,
            wifi_generation: 0,
            wifi_connecting: None,
            wifi_forgetting: None,
            wifi_forget_confirmation: None,
            wifi_password_prompt: None,
            wifi_enterprise_prompt: None,
            wifi_cancellation: None,
            wifi_on: false,
            wifi_interface: None,
            wifi_networks: Vec::new(),
            wifi_saved_networks: Vec::new(),

            bluetooth_available: false,
            bluetooth_loading: true,
            bluetooth_busy: false,
            bluetooth_generation: 0,
            bluetooth_discovering: false,
            bluetooth_adapter_name: None,
            bluetooth_on: false,
            bt_discoverable: false,
            bt_devices: Vec::new(),
            bluetooth_pairing: None,
            bluetooth_forget_confirmation: None,
            bluetooth_forgetting: None,

            host_appearance: rmac_appearance::Snapshot::default(),
            theme: None,
            theme_loading: true,
            theme_busy: false,
            theme_generation: 0,
            theme_refresh_pending: false,
            theme_stream_refreshing: false,
            gtk_text_loading: true,
            gtk_text_busy: false,
            gtk_text_generation: 0,
            gtk_text_refresh_pending: false,
            gtk_text_stream_refreshing: false,
            screen_reader_toggle_loading: true,
            screen_reader_toggle_busy: false,
            screen_reader_toggle_generation: 0,
            screen_reader_toggle_refresh_pending: false,
            screen_reader_toggle_stream_refreshing: false,

            privacy_loading: true,
            privacy_busy: None,
            privacy_reset_confirmation: None,
            privacy_generation: 0,
            privacy_refresh_pending: false,
            privacy_stream_refreshing: false,
            security_coverage_loading: true,

            audio_loading: true,
            audio_busy: false,
            audio_generation: 0,
            audio_refresh_pending: false,
            output_volume_generation: 0,
            input_volume_generation: 0,
            output_balance_generation: 0,
            output_volume,
            input_volume,
            output_balance,
            sound_policy,
            sound_policy_error,
            sound_policy_generation: 0,
            alert_volume,

            power_loading: true,
            power_busy: false,
            power_generation: 0,
            power_refresh_pending: false,

            display_loading: true,
            display_busy: false,
            display_generation: 0,
            display_refresh_pending: false,
            display_confirmation: None,

            input_loading: true,
            input_busy: false,
            input_generation: 0,
            input_refresh_pending: false,
            input_stream_refreshing: false,

            mac_keyboard: None,
            mac_keyboard_busy: false,
            mac_keyboard_error: None,
        }
    }
}
